//go:build linux

package providerimport_test

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/blang/semver"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostcontract"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostprotocol"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostruntime"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostruntime/testonly"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/program"
	"github.com/pulumi/pulumi/sdk/v3/go/auto"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optpreview"
	"github.com/pulumi/pulumi/sdk/v3/go/auto/optup"
	"github.com/pulumi/pulumi/sdk/v3/go/common/apitype"
	"github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors"
	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/config"
	sdkplugin "github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin"
	"github.com/pulumi/pulumi/sdk/v3/go/common/workspace"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	pulumirpc "github.com/pulumi/pulumi/sdk/v3/proto/go"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/structpb"
)

const (
	importRelease = "ghcr.io/example/sub2api-deploy@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	revisionKey   = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	hostType      = "sub2api-host:index:Host"
	hostName      = "host-edge"
	secretCanary  = "PROVIDER_IMPORT_SECRET_CANARY"
)

// TestProviderImportHelper is reached only through the test-owned SSH fixture.
// It invokes the production Runtime through the test-only construction seam.
func TestProviderImportHelper(t *testing.T) {
	if os.Getenv("SUB2API_PROVIDER_IMPORT_HELPER") != "1" {
		return
	}
	root := os.Getenv("PROVIDER_IMPORT_ROOT")
	machine := os.Getenv("PROVIDER_IMPORT_MACHINE_ID")
	digest := os.Getenv("PROVIDER_IMPORT_REQUEST_DIGEST")
	if err := testonly.ServeWithRequestDigest(os.Stdout, os.Stdin, root, machine, digest); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Exit(0)
}

// TestProviderImportDockerHelper is a guarded replacement for Docker. It only
// serves the exact inspect reads generated by the preseeded Runtime fixture.
func TestProviderImportDockerHelper(t *testing.T) {
	if os.Getenv("SUB2API_PROVIDER_IMPORT_DOCKER") != "1" {
		return
	}
	if err := runDockerReadHelper(os.Args); err != nil {
		writeForbiddenDockerRecord(sanitizeDockerError(err))
		os.Exit(64)
	}
	os.Exit(0)
}

// TestEngineImportPreviewIsNoOpOrAcceptedDiff runs a real Program Import through
// the official CLI and verifies a normal program preview cannot mutate the fixture.
func TestEngineImportPreviewIsNoOpOrAcceptedDiff(t *testing.T) {
	h := newHarness(t)
	h.setupRuntime(t)

	h.resetMeasuredTrace(t)
	beforeRoot := treeManifest(t, h.provider.root)
	imported, err := h.update(t, true)
	if err != nil {
		h.mu.Lock()
		calls := h.provider.recorder.snapshot()
		h.mu.Unlock()
		t.Fatalf("external Engine import update failed after calls=%v", calls)
	}
	h.assertImportResult(t, imported)
	h.assertMeasuredCalls(t, []string{"Configure", "Read", "Check", "Diff"})
	h.assertOneInspect(t)
	h.assertDockerReads(t, "read network-ls", "read network-ls", "read container-ls", "read app-readiness", "read container-ls", "read proxy-readiness")
	h.assertUnchangedRoot(t, beforeRoot)

	beforeSnapshot := imported
	h.resetMeasuredTrace(t)
	previewed, err := h.preview(t)
	if err != nil {
		t.Fatal("external Engine preview after import failed")
	}
	if !snapshotsEqual(beforeSnapshot, previewed) {
		t.Fatal("preview changed the imported checkpoint")
	}
	h.assertMeasuredCalls(t, []string{"Configure", "Check", "Diff"})
	h.assertNoEffects(t)
	h.assertDockerReads(t)
	h.assertUnchangedRoot(t, beforeRoot)
	h.assertNoCanaryLeak(t)
}

type harness struct {
	stack   auto.Stack
	root    string
	key     string
	providerBinary string

	provider *providerProcess

	mu                   sync.Mutex
	productionHostInputs resource.PropertyMap
	phase                string
	preseededState       hostruntime.State
	capturing            bool
}

func newHarness(t *testing.T) *harness {
	t.Helper()
	cli := os.Getenv("EXTERNAL_PULUMI_CLI")
	if cli == "" {
		cli = os.Getenv("ENGINE_GRAPH_PULUMI_CLI")
	}
	if cli == "" || !filepath.IsAbs(cli) {
		t.Fatal("external Pulumi CLI is required as an absolute path")
	}
	provider := os.Getenv("PROVIDER_IMPORT_BINARY")
	if provider == "" {
		provider = os.Getenv("SUB2API_TEST_PROVIDER_BINARY")
	}
	if provider == "" {
		if releaseRoot := os.Getenv("SUB2API_TEST_RELEASE_ROOT"); releaseRoot != "" {
			provider = filepath.Join(releaseRoot, "bin", "pulumi-resource-sub2api-host")
		}
	}
	if provider == "" || !filepath.IsAbs(provider) {
		t.Fatal("provider binary is required")
	}
	providerInfo, err := os.Stat(provider)
	if err != nil || !providerInfo.Mode().IsRegular() || providerInfo.Mode()&0o111 == 0 {
		t.Fatal("provider binary is unavailable")
	}
	versionOutput, err := exec.Command(cli, "version").Output()
	if err != nil || strings.TrimSpace(string(versionOutput)) != "v3.256.0" {
		t.Fatal("external Pulumi CLI must be pinned to v3.256.0")
	}
	root := t.TempDir()
	cliRoot := filepath.Join(root, "cli")
	if err := os.MkdirAll(filepath.Join(cliRoot, "bin"), 0o700); err != nil {
		t.Fatal("prepare CLI fixture failed")
	}
	if err := os.Symlink(cli, filepath.Join(cliRoot, "bin", "pulumi")); err != nil {
		t.Fatal("prepare CLI fixture failed")
	}
	command, err := auto.NewPulumiCommand(&auto.PulumiCommandOptions{Root: cliRoot, Version: semver.MustParse("3.256.0")})
	if err != nil {
		t.Fatal("initialize official Pulumi command failed")
	}
	backendRoot := t.TempDir()
	passphraseFile := filepath.Join(root, "config-passphrase")
	if err := os.WriteFile(passphraseFile, []byte("provider-import-test-passphrase\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	workspaceOptions := []auto.LocalWorkspaceOption{
		auto.WorkDir(root),
		auto.Pulumi(command),
		auto.PulumiHome(filepath.Join(root, "pulumi-home")),
		auto.SecretsProvider("passphrase"),
		auto.Project(workspace.Project{Name: "sub2api-environment", Runtime: workspace.NewProjectRuntimeInfo("go", nil)}),
		auto.EnvVars(map[string]string{
			"PATH":                         filepath.Dir(provider) + string(os.PathListSeparator) + os.Getenv("PATH"),
			"PULUMI_BACKEND_URL":           "file://" + filepath.ToSlash(backendRoot),
			"PULUMI_CONFIG_PASSPHRASE_FILE": passphraseFile,
			"PULUMI_SKIP_UPDATE_CHECK":      "true",
		}),
	}
	stack, err := auto.NewStackInlineSource(t.Context(), "canary", "sub2api-environment", func(ctx *pulumi.Context) error {
		return program.Register(ctx, importRelease, fixtureBytes("import.yaml"), fixtureBytes("import-secrets.yaml"))
	}, workspaceOptions...)
	if err != nil {
		t.Fatal("create Automation API stack failed")
	}
	return &harness{stack: stack, root: root, key: revisionKey, providerBinary: provider}
}

// setupRuntime creates a static, read-only Runtime fixture before the provider
// process exists. It intentionally never invokes Provider Create or bootstrap.
func (h *harness) setupRuntime(t *testing.T) {
	t.Helper()
	captureRoot, captureTrace := t.TempDir(), t.TempDir()
	if err := os.MkdirAll(filepath.Join(captureTrace, "current"), 0o700); err != nil {
		t.Fatal(err)
	}
	h.provider = startProvider(t, h.providerBinary, captureRoot, captureTrace, "")
	h.setProviderAttachPort(t)
	inputs := h.captureProductionInputs(t)
	stopProvider(t, h.provider)
	fixture := writePreseed(t, inputs)
	before := treeManifest(t, fixture.root)
	validatePreseed(t, fixture)
	if after := treeManifest(t, fixture.root); !reflect.DeepEqual(before, after) {
		t.Fatal("direct Runtime inspect changed the static fixture")
	}
	h.preseededState = fixture.state
	h.provider = startProvider(t, h.providerBinary, fixture.root, fixture.trace, filepath.Join(fixture.trace, "docker-model.json"))
	h.root = fixture.root
	h.setProviderAttachPort(t)
}

func (h *harness) setProviderAttachPort(t *testing.T) {
	t.Helper()
	h.stack.Workspace().SetEnvVar("PULUMI_DEBUG_PROVIDERS", "sub2api-host:"+h.provider.port)
}

func (h *harness) resetMeasuredTrace(t *testing.T) {
	t.Helper()
	h.provider.recorder.reset()

	newTraceGeneration(t, h.provider.trace)
}

func (h *harness) update(t *testing.T, importTarget bool) (apitype.UntypedDeployment, error) {
	return h.run(t, false, importTarget)
}

func (h *harness) preview(t *testing.T) (apitype.UntypedDeployment, error) {
	return h.run(t, true, false)
}

func (h *harness) run(t *testing.T, preview, importTarget bool) (apitype.UntypedDeployment, error) {
	t.Helper()
	phase := "preview"
	if !preview && importTarget {
		phase = "import"
	} else if !preview {
		phase = "update"
	}
	h.mu.Lock()
	if h.capturing { h.phase = "capture" } else { h.phase = phase }
	h.mu.Unlock()
	settings, err := h.stack.Workspace().StackSettings(t.Context(), h.stack.Name())
	if err != nil {
		return apitype.UntypedDeployment{}, err
	}
	saltParts := strings.SplitN(settings.EncryptionSalt, ":", 3)
	if len(saltParts) != 3 || saltParts[0] != "v1" {
		return apitype.UntypedDeployment{}, errors.New("invalid test secrets settings")
	}
	salt, err := base64.StdEncoding.DecodeString(saltParts[1])
	if err != nil {
		return apitype.UntypedDeployment{}, errors.New("invalid test secrets salt")
	}
	crypter := config.NewSymmetricCrypterFromPassphrase("provider-import-test-passphrase", salt)
	ciphertext, err := crypter.EncryptValue(t.Context(), h.key)
	if err != nil {
		return apitype.UntypedDeployment{}, errors.New("encrypt test config failed")
	}
	if settings.Config == nil {
		settings.Config = config.Map{}
	}
	settings.Config[config.MustMakeKey("sub2api-host", "revisionKey")] = config.NewSecureValue(ciphertext)
	hostImportTargetKey := config.MustMakeKey("sub2api-environment", "hostImportTarget")
	if importTarget {
		settings.Config[hostImportTargetKey] = config.NewValue("edge")
	} else {
		delete(settings.Config, hostImportTargetKey)
	}
	if err := h.stack.Workspace().SaveStackSettings(t.Context(), h.stack.Name(), settings); err != nil {
		return apitype.UntypedDeployment{}, err
	}
	if preview {
		_, err = h.stack.Preview(t.Context(), optpreview.Parallel(1), optpreview.Color(string(colors.Never)), optpreview.SuppressProgress(), optpreview.SuppressOutputs())
	} else {
		_, err = h.stack.Up(t.Context(), optup.Parallel(1), optup.Color(string(colors.Never)), optup.SuppressProgress(), optup.SuppressOutputs())
	}
	state, exportErr := h.stack.Export(t.Context())
	if err == nil { err = exportErr }
	return state, err
}

func decodePropertyJSON(value resource.PropertyValue, into any) bool {
	b, err := json.Marshal(unwrapFixtureValue(value).Mappable())
	return err == nil && json.Unmarshal(b, into) == nil
}
type providerProcess struct {
	cmd         *exec.Cmd
	client      pulumirpc.ResourceProviderClient
	conn        *grpc.ClientConn
	stdout      io.ReadCloser
	stderr      *lockedBuffer
	done        <-chan error
	identity    processIdentity
	root, trace, port string
	recorder *providerRecorder
	proxy    *grpc.Server
	proxyListener net.Listener
	stopOnce sync.Once
	stopped  chan struct{}
}

type providerRecorder struct {
	pulumirpc.UnimplementedResourceProviderServer
	upstream pulumirpc.ResourceProviderClient
	mu       sync.Mutex
	calls    []string
	inputs   resource.PropertyMap
}

func (p *providerRecorder) record(call string) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.calls = append(p.calls, call)
}
func (p *providerRecorder) reset() {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.calls = nil
	p.inputs = nil
}
func (p *providerRecorder) snapshot() []string {
	p.mu.Lock()
	defer p.mu.Unlock()
	return append([]string(nil), p.calls...)
}
func (p *providerRecorder) lastInputs() resource.PropertyMap {
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.inputs.Copy()
}
func (p *providerRecorder) Configure(ctx context.Context, req *pulumirpc.ConfigureRequest) (*pulumirpc.ConfigureResponse, error) {
	p.record("Configure")
	return p.upstream.Configure(ctx, req)
}
func (p *providerRecorder) Check(ctx context.Context, req *pulumirpc.CheckRequest) (*pulumirpc.CheckResponse, error) {
	p.record("Check")
	values := unmarshalProperties(req.GetNews())
	if _, ok := values[resource.PropertyKey("resource")]; ok {
		p.mu.Lock()
		p.inputs = values.Copy()
		p.mu.Unlock()
	}
	return p.upstream.Check(ctx, req)
}
func (p *providerRecorder) Diff(ctx context.Context, req *pulumirpc.DiffRequest) (*pulumirpc.DiffResponse, error) {
	p.record("Diff")
	return p.upstream.Diff(ctx, req)
}
func (p *providerRecorder) Read(ctx context.Context, req *pulumirpc.ReadRequest) (*pulumirpc.ReadResponse, error) {
	p.record("Read")
	return p.upstream.Read(ctx, req)
}
func (p *providerRecorder) Create(ctx context.Context, req *pulumirpc.CreateRequest) (*pulumirpc.CreateResponse, error) {
	p.record("Create")
	return p.upstream.Create(ctx, req)
}
func (p *providerRecorder) Update(ctx context.Context, req *pulumirpc.UpdateRequest) (*pulumirpc.UpdateResponse, error) {
	p.record("Update")
	return p.upstream.Update(ctx, req)
}
func (p *providerRecorder) Delete(ctx context.Context, req *pulumirpc.DeleteRequest) (*emptypb.Empty, error) {
	p.record("Delete")
	return p.upstream.Delete(ctx, req)
}
func (p *providerRecorder) Handshake(ctx context.Context, req *pulumirpc.ProviderHandshakeRequest) (*pulumirpc.ProviderHandshakeResponse, error) {
	return p.upstream.Handshake(ctx, req)
}
func (p *providerRecorder) Parameterize(ctx context.Context, req *pulumirpc.ParameterizeRequest) (*pulumirpc.ParameterizeResponse, error) {
	return p.upstream.Parameterize(ctx, req)
}
func (p *providerRecorder) GetSchema(ctx context.Context, req *pulumirpc.GetSchemaRequest) (*pulumirpc.GetSchemaResponse, error) {
	return p.upstream.GetSchema(ctx, req)
}
func (p *providerRecorder) CheckConfig(ctx context.Context, req *pulumirpc.CheckRequest) (*pulumirpc.CheckResponse, error) {
	return p.upstream.CheckConfig(ctx, req)
}
func (p *providerRecorder) DiffConfig(ctx context.Context, req *pulumirpc.DiffRequest) (*pulumirpc.DiffResponse, error) {
	return p.upstream.DiffConfig(ctx, req)
}
func (p *providerRecorder) GetPluginInfo(ctx context.Context, req *emptypb.Empty) (*pulumirpc.PluginInfo, error) {
	return p.upstream.GetPluginInfo(ctx, req)
}
func (p *providerRecorder) Attach(ctx context.Context, req *pulumirpc.PluginAttach) (*emptypb.Empty, error) {
	return p.upstream.Attach(ctx, req)
}
func (p *providerRecorder) Invoke(ctx context.Context, req *pulumirpc.InvokeRequest) (*pulumirpc.InvokeResponse, error) {
	return p.upstream.Invoke(ctx, req)
}
func (p *providerRecorder) Call(ctx context.Context, req *pulumirpc.CallRequest) (*pulumirpc.CallResponse, error) {
	return p.upstream.Call(ctx, req)
}
func (p *providerRecorder) Cancel(ctx context.Context, req *emptypb.Empty) (*emptypb.Empty, error) {
	return p.upstream.Cancel(ctx, req)
}
func (p *providerRecorder) Construct(ctx context.Context, req *pulumirpc.ConstructRequest) (*pulumirpc.ConstructResponse, error) {
	return p.upstream.Construct(ctx, req)
}
func (p *providerRecorder) GetMapping(ctx context.Context, req *pulumirpc.GetMappingRequest) (*pulumirpc.GetMappingResponse, error) {
	return p.upstream.GetMapping(ctx, req)
}
func (p *providerRecorder) GetMappings(ctx context.Context, req *pulumirpc.GetMappingsRequest) (*pulumirpc.GetMappingsResponse, error) {
	return p.upstream.GetMappings(ctx, req)
}
func (p *providerRecorder) List(req *pulumirpc.ListRequest, stream grpc.ServerStreamingServer[pulumirpc.ListResponse]) error {
	upstream, err := p.upstream.List(stream.Context(), req)
	if err != nil {
		return err
	}
	for {
		response, recvErr := upstream.Recv()
		if recvErr != nil {
			if recvErr == io.EOF {
				return nil
			}
			return recvErr
		}
		if err := stream.Send(response); err != nil {
			return err
		}
	}
}
type lockedBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *lockedBuffer) Write(value []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(value)
}
func (b *lockedBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}

type processIdentity struct {
	pid   int
	start string
}

type preseedFixture struct {
	root, machine, trace string
	model                dockerReadModel
	state                hostruntime.State
}

type dockerReadModel struct {
	NetworkName  string                     `json:"networkName"`
	NetworkOwner string                     `json:"networkOwner"`
	NetworkLabel string                     `json:"networkLabel"`
	Containers   map[string]dockerContainer `json:"containers"`
}

type dockerContainer struct {
	Owner         string `json:"owner"`
	Target        string `json:"target"`
	ReadinessPath string `json:"readinessPath"`
}

type fixtureInventory struct {
	Version         int                            `json:"version"`
	Resource        hostcontract.ResourceIdentity  `json:"resource"`
	Ownership       hostcontract.OwnershipIdentity `json:"ownership"`
	AppliedRevision string                         `json:"appliedRevision"`
	Objects         []fixtureManagedObject         `json:"objects"`
}

// fixtureManagedObject mirrors only hostruntime's private JSON inventory schema.
// It is fixture data, never a production replacement for that private type.
type fixtureManagedObject struct {
	Role          string                    `json:"role"`
	AppToken      string                    `json:"appToken,omitempty"`
	Name          string                    `json:"name"`
	Image         string                    `json:"image,omitempty"`
	Data          []fixtureManagedLink      `json:"data,omitempty"`
	Revision      string                    `json:"revision,omitempty"`
	Active        string                    `json:"active,omitempty"`
	Env           string                    `json:"env,omitempty"`
	Type          string                    `json:"type,omitempty"`
	Port          int                       `json:"port,omitempty"`
	Persistence   bool                      `json:"persistence,omitempty"`
	DataToken     string                    `json:"dataToken,omitempty"`
	PathToken     string                    `json:"pathToken,omitempty"`
	DataIdentity  hostcontract.DataIdentity `json:"dataIdentity,omitempty"`
	Config        string                    `json:"config,omitempty"`
	Hostname      string                    `json:"hostname,omitempty"`
	ReadinessPath string                    `json:"readinessPath,omitempty"`
	DrainSeconds  int                       `json:"drainSeconds,omitempty"`
}

type fixtureManagedLink struct {
	Name     string                    `json:"name"`
	Identity hostcontract.DataIdentity `json:"identity"`
}

type fixtureRouteDocument struct {
	HTTP fixtureRouteHTTP `json:"http"`
}
type fixtureRouteHTTP struct {
	Routers  map[string]fixtureRouter  `json:"routers"`
	Services map[string]fixtureService `json:"services"`
}
type fixtureRouter struct {
	Rule        string      `json:"rule"`
	EntryPoints []string    `json:"entryPoints"`
	Service     string      `json:"service"`
	TLS         *fixtureTLS `json:"tls,omitempty"`
}
type fixtureTLS struct {
	CertResolver string `json:"certResolver"`
}
type fixtureService struct {
	LoadBalancer fixtureLoadBalancer `json:"loadBalancer"`
}
type fixtureLoadBalancer struct {
	Servers []fixtureServer `json:"servers"`
}
type fixtureServer struct {
	URL string `json:"url"`
}

func writePreseed(t *testing.T, inputs resource.PropertyMap) preseedFixture {
	t.Helper()
	caseDir := t.TempDir()
	root := filepath.Join(caseDir, "state")
	trace := filepath.Join(caseDir, "trace")
	machinePath := filepath.Join(caseDir, "machine-id")
	for _, path := range []string{root, trace, filepath.Join(root, "runtime", "managed"), filepath.Join(root, "runtime", "dynamic"), filepath.Join(root, "runtime", "data")} {
		if err := os.MkdirAll(path, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	bin := filepath.Join(caseDir, "bin")
	if err := os.MkdirAll(bin, 0o700); err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(bin, "docker"), dockerShim(), 0o700)
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("PROVIDER_IMPORT_TRACE", trace)
	t.Setenv("PROVIDER_IMPORT_TEST_BINARY", os.Args[0])
	t.Setenv("PROVIDER_IMPORT_DOCKER_MODEL", filepath.Join(trace, "docker-model.json"))
	writeFixture(t, machinePath, []byte("0123456789abcdef0123456789abcdef\n"), 0o600)
	resourceValue, target, secretValues := decodeFixtureInputs(t, inputs)
	machine := fixtureMachineIdentity()
	ownership := hostcontract.OwnershipIdentity{Value: "oid1:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"}
	revision := fixtureRevision(t, resourceValue, target, secretValues)
	writeFixture(t, filepath.Join(bin, "nft"), nftShim(fixtureNftTableName(resourceValue, ownership)), 0o700)
	appToken := fixtureToken("app", "app")
	appName := fixtureObjectName(resourceValue, ownership, "app", appToken, "green")
	proxyName := fixtureObjectName(resourceValue, ownership, "proxy", "proxy", "live")
	appEnv := "env-" + appToken + fixtureToken(revision)
	proxyToken := fixtureToken("proxy")
	proxyEnv := "env-" + proxyToken + fixtureToken(revision)
	proxyConfig := "config-" + fixtureToken("proxy", revision)
	app := target.Apps[0]
	inventory := fixtureInventory{Version: 3, Resource: resourceValue, Ownership: ownership, AppliedRevision: revision, Objects: []fixtureManagedObject{
		{Role: "app", AppToken: appToken, Name: appName, Image: app.Image, Data: fixtureLinks(app.DataLinks), Revision: revision, Active: "green", Env: appEnv, Hostname: app.Hostname, ReadinessPath: app.ReadinessPath, DrainSeconds: 30},
		{Role: "proxy", Name: proxyName, Image: target.ReverseProxy.Image, Revision: revision, Env: proxyEnv, Config: proxyConfig},
	}}
	writeJSONFixture(t, filepath.Join(root, "runtime", "managed", "inventory.json"), inventory, 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", appEnv), fixtureAppEnv(secretValues), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", proxyEnv), []byte("CF_DNS_API_TOKEN="+secretValues.ReverseProxy.DNSChallengeToken+"\n"), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", proxyConfig), fixtureProxyConfig(target.ReverseProxy.ACMEEmail), 0o600)
	dataDir := filepath.Join(root, "runtime", "data", fixtureToken("app-data", appToken))
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(dataDir, "sentinel"), []byte("persistent-data-sentinel\n"), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "dynamic", "route-"+appToken+".json"), fixtureRoute(resourceValue, ownership, appToken, appName, revision, app.Hostname), 0o600)
	observation := hostcontract.StableObservation{Machine: machine, Ownership: ownership, HostRelease: target.ReleaseArtifact, AppliedRevision: revision, Ready: true, Apps: []hostcontract.AppObservation{{ID: app.ID, ActiveImage: app.Image, Ready: true}}}
	state := hostruntime.State{Version: 1, Resource: resourceValue, Machine: machine, Ownership: ownership, AppliedRevision: revision, Observation: observation}
	writeJSONFixture(t, filepath.Join(root, "state.json"), state, 0o600)
	model := dockerReadModel{NetworkName: fixtureNetworkName(resourceValue, ownership), NetworkOwner: fixtureOwnershipLabel(resourceValue, ownership, "network", "", ""), NetworkLabel: fixtureNetworkLabel(resourceValue, ownership), Containers: map[string]dockerContainer{
		appName:   {Owner: fixtureOwnershipLabel(resourceValue, ownership, "app", appToken, "green"), Target: fixtureTargetLabel("app", appToken, "green", revision, app.Image), ReadinessPath: app.ReadinessPath},
		proxyName: {Owner: fixtureOwnershipLabel(resourceValue, ownership, "proxy", "", ""), Target: fixtureTargetLabel("proxy", "", "", revision, target.ReverseProxy.Image), ReadinessPath: ""},
	}}
	writeJSONFixture(t, filepath.Join(trace, "docker-model.json"), model, 0o600)
	newTraceGeneration(t, trace)
	return preseedFixture{root: root, machine: machinePath, trace: trace, model: model, state: state}
}

func validatePreseed(t *testing.T, fixture preseedFixture) {
	t.Helper()
	request := hostprotocol.Request{Action: hostcontract.ActionInspect, Server: hostcontract.ServerTarget{SSHAlias: "edge"}, Resource: hostcontract.ResourceIdentity{Environment: "canary", ServerKey: "edge"}, TargetRevision: readFixtureRevision(t, fixture.root)}
	frame, err := hostprotocol.EncodeRequest(request)
	if err != nil {
		t.Fatal(err)
	}
	var response bytes.Buffer
	digest := filepath.Join(fixture.trace, "preseed.digest")
	if err := testonly.ServeWithRequestDigest(&response, bytes.NewReader(frame), fixture.root, fixture.machine, digest); err != nil {
		t.Fatal("direct preseed inspect failed")
	}
	decoded, err := hostprotocol.DecodeResponse(response.Bytes())
	if err != nil || decoded.Result == nil || decoded.Result.Observation == nil || !decoded.Result.Observation.Ready || decoded.Result.Observation.Drifted {
		var errorCategory hostprotocol.ErrorCategory
		var errorCode hostprotocol.ErrorCode
		if decoded.Error != nil {
			errorCategory = decoded.Error.Category
			errorCode = decoded.Error.Code
		}
		t.Fatalf("direct preseed inspect did not return a ready observation: category=preseed-inspect error-category=%q error-code=%q", errorCategory, errorCode)
	}
}

func readTraceFile(trace, name string) string {
	b, _ := os.ReadFile(filepath.Join(trace, "current", name))
	return string(b)
}

func decodeFixtureInputs(t *testing.T, inputs resource.PropertyMap) (hostcontract.ResourceIdentity, hostcontract.Target, hostcontract.Secrets) {
	t.Helper()
	var resourceValue hostcontract.ResourceIdentity
	var target hostcontract.Target
	var secretValues hostcontract.Secrets
	decode := func(name string, into any) {
		b, err := json.Marshal(unwrapFixtureValue(inputs[resource.PropertyKey(name)]).Mappable())
		if err != nil {
			t.Fatal(err)
		}
		if err = json.Unmarshal(b, into); err != nil {
			t.Fatal(err)
		}
	}
	decode("resource", &resourceValue)
	decode("target", &target)
	decode("secrets", &secretValues)
	if resourceValue != (hostcontract.ResourceIdentity{Environment: "canary", ServerKey: "edge"}) || len(target.Apps) != 1 || target.ReverseProxy == nil {
		t.Fatal("unexpected import fixture shape")
	}
	return resourceValue, target, secretValues
}

func unwrapFixtureValue(value resource.PropertyValue) resource.PropertyValue {
	for value.IsSecret() {
		value = value.SecretValue().Element
	}
	return value
}

func fixtureMachineIdentity() hostcontract.MachineIdentity {
	return hostcontract.MachineIdentity{Value: "mid1:0911601b3b0a5f6fdc51f3661518ee20e26ea0cbadfb4f7283e5b1f288941f54"}
}
func fixtureRevision(t *testing.T, resourceValue hostcontract.ResourceIdentity, target hostcontract.Target, secretValues hostcontract.Secrets) string {
	t.Helper()
	key, err := base64.StdEncoding.DecodeString(revisionKey)
	if err != nil {
		t.Fatal(err)
	}
	revision, err := hostcontract.TargetRevision(hostcontract.RevisionKey(key), resourceValue, target, secretValues)
	if err != nil {
		t.Fatal("fixture target revision failed")
	}
	return revision
}
func fixtureLinks(links []hostcontract.DataLink) []fixtureManagedLink {
	out := make([]fixtureManagedLink, len(links))
	for i, link := range links {
		out[i] = fixtureManagedLink{Name: link.Name, Identity: link.Identity}
	}
	return out
}
func fixtureToken(values ...string) string {
	h := sha256.New()
	for _, value := range values {
		_, _ = h.Write([]byte(value))
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil)[:12])
}
func fixtureObjectName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, role, app, slot string) string {
	return "s2h-" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value, role, app, slot)
}
func fixtureOwnershipLabel(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, role, app, slot string) string {
	return "s2h1:" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value, role, app, slot)
}
func fixtureTargetLabel(role, app, active, revision, image string) string {
	return "s2ht1:" + fixtureToken(role, app, active, revision, image, "", "0", "false")
}
func fixtureNetworkName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2h-net-" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureNftTableName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2h_" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureNetworkLabel(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2hnet1:" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureAppEnv(secrets hostcontract.Secrets) []byte {
	app := secrets.Apps["app"]
	return []byte("ADMIN_EMAIL=admin@example.test\nFEATURE_FLAG=enabled\nINITIAL_ADMIN_PASSWORD=" + app.InitialAdminPassword + "\nJWT_SECRET=" + app.JWTSecret + "\nTOTP_ENCRYPTION_KEY=" + app.TOTPEncryptionKey + "\nPOSTGRES_USERNAME=" + app.Postgres.Username + "\nPOSTGRES_PASSWORD=" + app.Postgres.Password + "\nREDIS_USERNAME=" + app.Redis.Username + "\nREDIS_PASSWORD=" + app.Redis.Password + "\n")
}
func fixtureProxyConfig(email string) []byte {
	return []byte("entryPoints:\n  web:\n    address: \":80\"\n  websecure:\n    address: \":443\"\n  probe:\n    address: \":8081\"\nproviders:\n  file:\n    directory: /etc/traefik/dynamic\n    watch: true\ncertificatesResolvers:\n  cloudflare:\n    acme:\n      email: " + strconv.Quote(email) + "\n      storage: /etc/traefik/acme.json\n      dnsChallenge:\n        provider: cloudflare\n")
}
func fixtureRoute(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, token, name, revision, hostname string) []byte {
	key := fixtureToken("route", resourceValue.Environment, resourceValue.ServerKey, ownership.Value, token, revision, "green", name)
	service := fixtureToken("service", key)
	route := fixtureRouteDocument{HTTP: fixtureRouteHTTP{
		Routers: map[string]fixtureRouter{
			fixtureToken("router", "public", key): {Rule: "Host(`" + hostname + "`)", EntryPoints: []string{"websecure"}, Service: service, TLS: &fixtureTLS{CertResolver: "cloudflare"}},
			fixtureToken("router", "probe", key):  {Rule: "Host(`" + hostname + "`)", EntryPoints: []string{"probe"}, Service: service},
		},
		Services: map[string]fixtureService{service: {LoadBalancer: fixtureLoadBalancer{Servers: []fixtureServer{{URL: "http://" + name + ":8080"}}}}},
	}}
	b, _ := json.Marshal(route)
	return b
}
func readFixtureRevision(t *testing.T, root string) string {
	t.Helper()
	var state hostruntime.State
	b, err := os.ReadFile(filepath.Join(root, "state.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(b, &state); err != nil {
		t.Fatal(err)
	}
	return state.AppliedRevision
}
func writeJSONFixture(t *testing.T, path string, value any, mode os.FileMode) {
	t.Helper()
	b, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, path, b, mode)
}

func dockerShim() []byte {
	return []byte("#!/bin/sh\nexec env SUB2API_PROVIDER_IMPORT_DOCKER=1 \"$PROVIDER_IMPORT_TEST_BINARY\" -test.run '^TestProviderImportDockerHelper$' -- \"$@\"\n")
}

func nftShim(table string) []byte {
	return []byte("#!/bin/sh\nif [ \"$#\" -eq 5 ] && [ \"$1\" = \"-j\" ] && [ \"$2\" = \"list\" ] && [ \"$3\" = \"table\" ] && [ \"$4\" = \"inet\" ] && [ \"$5\" = \"" + table + "\" ]; then\n  printf '%s\\n' 'Error: No such file or directory' >&2\n  exit 1\nfi\nprintf '%s\\n' 'unsupported nft invocation' >&2\nexit 64\n")
}

func runDockerReadHelper(argv []string) error {
	separator := -1
	for i, value := range argv {
		if value == "--" {
			separator = i
			break
		}
	}
	if separator < 0 || separator == len(argv)-1 {
		return errors.New("missing docker arguments")
	}
	var model dockerReadModel
	b, err := os.ReadFile(os.Getenv("PROVIDER_IMPORT_DOCKER_MODEL"))
	if err != nil || json.Unmarshal(b, &model) != nil {
		return errors.New("invalid docker model")
	}
	args := argv[separator+1:]
	network := []string{"network", "ls", "--filter", "name=^" + model.NetworkName + "$", "--format", "{{.Name}}\t{{.Label \"sub2api.host\"}}\t{{.Label \"sub2api.host.network\"}}"}
	if reflect.DeepEqual(args, network) {
		_, err = fmt.Fprintf(os.Stdout, "%s\t%s\t%s\n", model.NetworkName, model.NetworkOwner, model.NetworkLabel)
		if err == nil {
			writeDockerRecord("read network-ls")
		}
		return err
	}
	if len(args) == 7 && args[0] == "container" && args[1] == "ls" && args[2] == "--all" && args[3] == "--filter" && strings.HasPrefix(args[4], "name=^/") && strings.HasSuffix(args[4], "$") && args[5] == "--format" && args[6] == "{{.Names}}\t{{.Label \"sub2api.host\"}}\t{{.Label \"sub2api.host.target\"}}" {
		name := strings.TrimSuffix(strings.TrimPrefix(args[4], "name=^/"), "$")
		container, ok := model.Containers[name]
		if !ok {
			return errors.New("unknown inspect container")
		}
		_, err = fmt.Fprintf(os.Stdout, "%s\t%s\t%s\n", name, container.Owner, container.Target)
		if err == nil {
			writeDockerRecord("read container-ls")
		}
		return err
	}
	if len(args) == 7 && args[0] == "exec" && args[2] == "wget" && args[3] == "-q" && args[4] == "-O" && args[5] == "/dev/null" {
		container, ok := model.Containers[args[1]]
		if !ok || args[6] != "http://localhost:8080"+container.ReadinessPath {
			return errors.New("invalid app readiness")
		}
		writeDockerRecord("read app-readiness")
		return nil
	}
	if len(args) == 4 && args[0] == "exec" && args[2] == "traefik" && args[3] == "version" {
		container, ok := model.Containers[args[1]]
		if !ok || container.ReadinessPath != "" {
			return errors.New("invalid proxy readiness")
		}
		writeDockerRecord("read proxy-readiness")
		return nil
	}
	return errors.New("forbidden docker mutation or unsupported read")
}

func writeDockerRecord(record string) {
	trace := os.Getenv("PROVIDER_IMPORT_TRACE")
	file, err := os.OpenFile(filepath.Join(trace, "current", "docker-reads"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return
	}
	defer file.Close()
	_, _ = file.WriteString(record + "\n")
}

func writeForbiddenDockerRecord(record string) {
	trace := os.Getenv("PROVIDER_IMPORT_TRACE")
	path := filepath.Join(trace, "current", "forbidden")
	_ = os.WriteFile(path, []byte(record+"\n"), 0o600)
}

func sanitizeDockerError(err error) string {
	return strings.NewReplacer("\n", " ", "\r", " ", "\x00", " ").Replace(err.Error())
}

func newTraceGeneration(t *testing.T, trace string) {
	t.Helper()
	name := fmt.Sprintf("%d-%s", time.Now().UnixNano(), fixtureToken(t.Name()))
	if err := os.MkdirAll(filepath.Join(trace, "generations", name), 0o700); err != nil {
		t.Fatal(err)
	}
	temporary := filepath.Join(trace, ".current-"+name)
	if err := os.Symlink(filepath.Join("generations", name), temporary); err != nil {
		t.Fatal(err)
	}
	if err := os.Rename(temporary, filepath.Join(trace, "current")); err != nil {
		t.Fatal(err)
	}
}

func startProvider(t *testing.T, binary, root, trace, dockerModel string) *providerProcess {
	t.Helper()
	caseDir := filepath.Dir(root)
	bin := filepath.Join(caseDir, "bin")
	for _, path := range []string{bin} {
		if err := os.MkdirAll(path, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	writeFixture(t, filepath.Join(bin, "ssh"), fixtureFile(t, "ssh-import.sh"), 0o700)
	writeFixture(t, filepath.Join(bin, "docker"), dockerShim(), 0o700)
	cmd := exec.Command(binary)
	cmd.Dir = filepath.Dir(binary)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Env = append(os.Environ(),
		"PATH="+bin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"PROVIDER_IMPORT_TRACE="+trace,
		"PROVIDER_IMPORT_ROOT="+root,
		"PROVIDER_IMPORT_MACHINE_ID="+filepath.Join(caseDir, "machine-id"),
		"PROVIDER_IMPORT_TEST_BINARY="+os.Args[0],
		"PROVIDER_IMPORT_REQUEST_DIGEST="+filepath.Join(trace, "current", "request.digest"),
		"PROVIDER_IMPORT_DOCKER_MODEL="+dockerModel,
	)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatal(err)
	}
	stderr := &lockedBuffer{}
	cmd.Stderr = stderr
	if err = cmd.Start(); err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	identity := processIdentity{pid: cmd.Process.Pid, start: processStart(cmd.Process.Pid)}
	port := readPort(t, stdout)
	ctx, cancelDial := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancelDial()
	conn, err := grpc.DialContext(ctx, net.JoinHostPort("127.0.0.1", port), grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock())
	if err != nil {
		t.Fatal(err)
	}
	recorder := &providerRecorder{upstream: pulumirpc.NewResourceProviderClient(conn)}
	proxyListener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil { t.Fatal(err) }
	proxy := grpc.NewServer()
	pulumirpc.RegisterResourceProviderServer(proxy, recorder)
	go func() { _ = proxy.Serve(proxyListener) }()
	p := &providerProcess{cmd: cmd, client: pulumirpc.NewResourceProviderClient(conn), conn: conn, stdout: stdout, stderr: stderr, done: done, identity: identity, root: root, trace: trace, port: strconv.Itoa(proxyListener.Addr().(*net.TCPAddr).Port), recorder: recorder, proxy: proxy, proxyListener: proxyListener, stopped: make(chan struct{})}
	t.Cleanup(func() { _ = conn.Close(); _ = stdout.Close(); stopProvider(t, p) })
	ctx, cancelConfigure := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancelConfigure()
	if _, err := p.client.Configure(ctx, &pulumirpc.ConfigureRequest{Args: resourceRPCProperties(t, resource.PropertyMap{"revisionKey": resource.MakeSecret(resource.NewStringProperty(revisionKey))})}); err != nil {
		t.Fatal(err)
	}
	return p
}

func (h *harness) captureProductionInputs(t *testing.T) resource.PropertyMap {
	h.provider.recorder.reset()
	h.mu.Lock()
	h.capturing = true
	h.phase = "capture"
	h.mu.Unlock()
	defer func() {
		h.mu.Lock()
		h.capturing = false
		h.mu.Unlock()
	}()
	_, err := h.run(t, true, false)
	if err != nil {
		t.Fatal("capture production inputs failed")
	}
	inputs := h.provider.recorder.lastInputs()
	if inputs == nil {
		t.Fatal("program did not register Host")
	}
	h.productionHostInputs = inputs
	return inputs.Copy()
}
func (h *harness) stableID() string {
	sum := sha256.Sum256([]byte("sub2api-host-resource-id-v1:6:canary4:edge"))
	return "host-" + hex.EncodeToString(sum[:])
}
func (h *harness) assertImportResult(t *testing.T, deployment apitype.UntypedDeployment) {
	state := singleHost(t, deployment)
	preseeded := h.preseededState
	if string(state.URN) != hostURN() {
		t.Fatalf("Host URN = %q, want %q", state.URN, hostURN())
	}
	if !strings.HasPrefix(string(state.ImportID), "hit1:") || state.ID != resource.ID(h.stableID()) {
		t.Fatalf("Host state did not preserve the import token")
	}
	assertCanonicalHostInputs(t, deploymentPropertyMap(t, state.Inputs), h.productionHostInputs)
	assertImportedCheckpoint(t, state, preseeded)
	if !secretOnlyProperty(deploymentPropertyMap(t, state.Outputs), secretCanary, false) {
		t.Fatal("import checkpoint exposes the secret canary outside a secret property")
	}
}
func assertImportedCheckpoint(t *testing.T, state apitype.ResourceV3, expected hostruntime.State) {
	t.Helper()
	var machine hostcontract.MachineIdentity
	var ownership hostcontract.OwnershipIdentity
	var revision string
	var observation hostcontract.StableObservation
	for _, item := range []struct {
		name string
		into any
	}{{"machine", &machine}, {"ownership", &ownership}, {"appliedRevision", &revision}, {"observation", &observation}} {
		value, ok := state.Outputs[string(item.name)]
		if !ok || !decodeJSONValue(value, item.into) {
			t.Fatalf("import checkpoint output %s is missing, secret, unknown, or invalid", item.name)
		}
	}
	if machine != expected.Machine || ownership != expected.Ownership || revision != expected.AppliedRevision || !reflect.DeepEqual(observation, expected.Observation) {
		t.Fatal("import checkpoint outputs differ from preseeded Runtime state")
	}
}
func decodeJSONValue(value any, into any) bool {
	b, err := json.Marshal(value)
	return err == nil && json.Unmarshal(b, into) == nil
}
func deploymentPropertyMap(t *testing.T, values map[string]any) resource.PropertyMap {
	t.Helper()
	object, err := structpb.NewStruct(values)
	if err != nil {
		t.Fatal("decode deployment properties")
	}
	return unmarshalProperties(object)
}
func secretOnlyProperty(values resource.PropertyMap, canary string, secret bool) bool {
	for _, value := range values {
		if !secretOnlyValue(value, canary, secret) {
			return false
		}
	}
	return true
}
func secretOnlyValue(value resource.PropertyValue, canary string, secret bool) bool {
	if value.IsSecret() {
		return secretOnlyValue(value.SecretValue().Element, canary, true)
	}
	if value.IsString() {
		return !strings.Contains(value.StringValue(), canary) || secret
	}
	if value.IsArray() {
		for _, child := range value.ArrayValue() {
			if !secretOnlyValue(child, canary, secret) {
				return false
			}
		}
	}
	if value.IsObject() {
		for _, child := range value.ObjectValue() {
			if !secretOnlyValue(child, canary, secret) {
				return false
			}
		}
	}
	return true
}
func assertCanonicalHostInputs(t *testing.T, imported, programInputs resource.PropertyMap) {
	t.Helper()
	if len(imported) != 4 || len(programInputs) != 4 {
		t.Fatal("Host inputs do not have the complete expected top-level shape")
	}
	for _, key := range []resource.PropertyKey{"resource", "server", "target", "secrets"} {
		importedValue, importedOK := imported[key]
		programValue, programOK := programInputs[key]
		if !importedOK || !programOK || importedValue.ContainsSecrets() != programValue.ContainsSecrets() {
			t.Fatalf("import checkpoint %s differs in presence or secret classification", key)
		}
	}
	for _, key := range []resource.PropertyKey{"resource", "server"} {
		if !reflect.DeepEqual(imported[key], programInputs[key]) {
			t.Fatalf("import checkpoint %s differs from the registered Host input", key)
		}
	}
	var importedTarget, programTarget hostcontract.Target
	var importedSecrets, programSecrets hostcontract.Secrets
	if !decodePropertyJSON(imported["target"], &importedTarget) || !decodePropertyJSON(programInputs["target"], &programTarget) || !decodePropertyJSON(imported["secrets"], &importedSecrets) || !decodePropertyJSON(programInputs["secrets"], &programSecrets) {
		t.Fatal("decode canonical Host inputs")
	}
	importedTarget, importedSecrets = hostcontract.NormalizeTargetSecrets(importedTarget, importedSecrets)
	programTarget, programSecrets = hostcontract.NormalizeTargetSecrets(programTarget, programSecrets)
	if !reflect.DeepEqual(importedTarget, programTarget) || !reflect.DeepEqual(importedSecrets, programSecrets) {
		t.Fatal("import checkpoint Host inputs differ from program inputs")
	}
}
func (h *harness) assertMeasuredCalls(t *testing.T, want []string) {
	got := h.provider.recorder.snapshot()
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("provider calls = %v, want %v", got, want)
	}
}
func (h *harness) assertOneInspect(t *testing.T) {
	value, err := os.ReadFile(filepath.Join(h.provider.trace, "current", "request.digest"))
	if err != nil {
		t.Fatalf("read inspect digest: %v", err)
	}
	want, err := expectedInspectDigest(h.productionHostInputs)
	if err != nil {
		t.Fatal(err)
	}
	if string(value) != want {
		t.Fatalf("inspect digest metadata differs")
	}
}
func expectedInspectDigest(inputs resource.PropertyMap) (string, error) {
	targetJSON, err := json.Marshal(unwrapFixtureValue(inputs["target"]).Mappable())
	if err != nil {
		return "", err
	}
	resourceJSON, err := json.Marshal(unwrapFixtureValue(inputs["resource"]).Mappable())
	if err != nil {
		return "", err
	}
	secretsJSON, err := json.Marshal(unwrapFixtureValue(inputs["secrets"]).Mappable())
	if err != nil {
		return "", err
	}
	var targetValue hostcontract.Target
	var identity hostcontract.ResourceIdentity
	var secretValues hostcontract.Secrets
	if err := json.Unmarshal(targetJSON, &targetValue); err != nil {
		return "", err
	}
	if err := json.Unmarshal(resourceJSON, &identity); err != nil {
		return "", err
	}
	if err := json.Unmarshal(secretsJSON, &secretValues); err != nil {
		return "", err
	}
	key, err := base64.StdEncoding.DecodeString(revisionKey)
	if err != nil {
		return "", err
	}
	revision, err := hostcontract.TargetRevision(hostcontract.RevisionKey(key), identity, targetValue, secretValues)
	if err != nil {
		return "", err
	}
	frame, err := hostprotocol.EncodeRequest(hostprotocol.Request{Action: hostcontract.ActionInspect, Server: hostcontract.ServerTarget{SSHAlias: "edge"}, Resource: identity, TargetRevision: revision})
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(frame)
	return fmt.Sprintf("operationDigest=%x\naction=inspect\n", sum), nil
}
func (h *harness) assertNoEffects(t *testing.T) {
	for _, name := range []string{"docker-effects", "forbidden"} {
		b, err := os.ReadFile(filepath.Join(h.provider.trace, "current", name))
		if err == nil && strings.TrimSpace(string(b)) != "" {
			t.Fatalf("measured phase emitted forbidden Docker effects")
		}
	}
}
func (h *harness) assertDockerReads(t *testing.T, want ...string) {
	b, err := os.ReadFile(filepath.Join(h.provider.trace, "current", "docker-reads"))
	if len(want) == 0 {
		if err == nil && strings.TrimSpace(string(b)) != "" {
			t.Fatalf("unexpected Docker reads")
		}
		return
	}
	if err != nil {
		t.Fatalf("read Docker trace: %v", err)
	}
	got := strings.Fields(strings.TrimSpace(string(b)))
	var actions []string
	for i := 0; i+1 < len(got); i += 2 {
		actions = append(actions, got[i]+" "+got[i+1])
	}
	if !reflect.DeepEqual(actions, want) {
		t.Fatalf("Docker inspect reads = %v, want %v", actions, want)
	}
}
func (h *harness) assertUnchangedRoot(t *testing.T, before map[string]string) {
	if after := treeManifest(t, h.provider.root); !reflect.DeepEqual(before, after) {
		t.Fatal("runtime state changed during measured phase")
	}
}
func (h *harness) assertNoCanaryLeak(t *testing.T) {
	if strings.Contains(h.provider.stderr.String(), secretCanary) {
		t.Fatal("secret canary leaked to provider diagnostics")
	}
	for _, root := range []string{h.provider.trace, h.provider.root} {
		if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
				return nil
			}
			b, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			// Secret-bearing Runtime env files are the sole deliberate exception.
			if strings.Contains(string(b), secretCanary) && !strings.HasPrefix(path, filepath.Join(h.provider.root, "runtime", "managed", "env-")) {
				t.Fatalf("secret canary leaked to %s", path)
			}
			return nil
		}); err != nil {
			t.Fatalf("secret canary scan failed: %v", err)
		}
	}
}
func treeManifest(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if relative == "." {
			relative = ""
		}
		mode := info.Mode()
		switch {
		case mode.IsDir():
			out[relative] = fmt.Sprintf("dir:%o", mode.Perm())
		case mode.IsRegular():
			b, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			sum := sha256.Sum256(b)
			out[relative] = fmt.Sprintf("file:%o:%x", mode.Perm(), sum)
		case mode&os.ModeSymlink != 0:
			target, readErr := os.Readlink(path)
			if readErr != nil {
				return readErr
			}
			out[relative] = fmt.Sprintf("symlink:%o:%s", mode.Perm(), target)
		default:
			return fmt.Errorf("unsupported fixture file type at %s: %s", relative, mode.Type())
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	return out
}
func resourceRPCProperties(t *testing.T, values resource.PropertyMap) *structpb.Struct {
	encoded, err := sdkplugin.MarshalProperties(values, sdkplugin.MarshalOptions{KeepUnknowns: true, KeepSecrets: true, KeepResources: true})
	if err != nil {
		if t != nil {
			t.Fatal(err)
		}
		panic(err)
	}
	return encoded
}
func unmarshalProperties(value *structpb.Struct) resource.PropertyMap {
	decoded, err := sdkplugin.UnmarshalProperties(value, sdkplugin.MarshalOptions{KeepUnknowns: true, KeepSecrets: true, KeepResources: true})
	if err != nil {
		panic("invalid provider property payload")
	}
	return decoded
}
func fixtureFile(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	return b
}
func fixtureBytes(name string) []byte {
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		panic(err)
	}
	return b
}
func writeFixture(t *testing.T, path string, value []byte, mode os.FileMode) {
	t.Helper()
	if err := os.WriteFile(path, value, mode); err != nil {
		t.Fatal(err)
	}
}
func hostURN() string { return "urn:pulumi:canary::sub2api-environment::" + hostType + "::" + hostName }
func singleHost(t *testing.T, deployment apitype.UntypedDeployment) apitype.ResourceV3 {
	t.Helper()
	var typed apitype.DeploymentV3
	if err := json.Unmarshal(deployment.Deployment, &typed); err != nil {
		t.Fatal("decode exported deployment")
	}
	for _, state := range typed.Resources {
		if state.Type == hostType {
			return state
		}
	}
	t.Fatal("checkpoint has no Host")
	return apitype.ResourceV3{}
}
func snapshotsEqual(a, b apitype.UntypedDeployment) bool {
	return reflect.DeepEqual(a, b)
}
func readPort(t *testing.T, reader io.Reader) string {
	t.Helper()
	result := make(chan struct {
		line string
		err  error
	}, 1)
	go func() {
		line, err := bufio.NewReader(reader).ReadString('\n')
		result <- struct {
			line string
			err  error
		}{line, err}
	}()
	select {
	case value := <-result:
		if value.err != nil {
			t.Fatal(value.err)
		}
		port := strings.TrimSpace(value.line)
		if _, err := strconv.Atoi(port); err != nil {
			t.Fatalf("invalid provider port %q", port)
		}
		return port
	case <-time.After(5 * time.Second):
		t.Fatal("provider did not emit a port within 5 seconds")
		return ""
	}
}
func processStart(pid int) string {
	b, err := os.ReadFile(fmt.Sprintf("/proc/%d/stat", pid))
	if err != nil {
		return ""
	}
	close := strings.LastIndexByte(string(b), ')')
	fields := strings.Fields(string(b)[close+1:])
	if len(fields) < 20 {
		return ""
	}
	return fields[19]
}
func stopProvider(t *testing.T, p *providerProcess) {
	t.Helper()
	p.stopOnce.Do(func() {
		defer close(p.stopped)
		if p.proxy != nil {
			p.proxy.Stop()
		}
		if p.proxyListener != nil {
			_ = p.proxyListener.Close()
		}
		if p.identity.start != "" && processStart(p.identity.pid) == p.identity.start {
			_ = syscall.Kill(-p.identity.pid, syscall.SIGTERM)
		}
		select {
		case <-p.done:
			return
		case <-time.After(time.Second):
		}
		if p.identity.start != "" && processStart(p.identity.pid) == p.identity.start {
			_ = syscall.Kill(-p.identity.pid, syscall.SIGKILL)
		}
		select {
		case <-p.done:
		case <-time.After(time.Second):
			t.Errorf("provider process did not exit")
		}
	})
	<-p.stopped
}
