//go:build linux

package providerimport_test

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"syscall"
	"testing"
	"time"

	"github.com/blang/semver"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostcontract"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostprotocol"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostruntime"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/hostruntime/testonly"
	"github.com/c-w-xiaohei/sub2api-deploy/internal/program"
	"github.com/pulumi/pulumi/pkg/v3/backend"
	"github.com/pulumi/pulumi/pkg/v3/backend/display"
	"github.com/pulumi/pulumi/pkg/v3/backend/diy"
	pulumidisplay "github.com/pulumi/pulumi/pkg/v3/display"
	"github.com/pulumi/pulumi/pkg/v3/engine"
	pkgresource "github.com/pulumi/pulumi/pkg/v3/resource"
	"github.com/pulumi/pulumi/pkg/v3/resource/deploy"
	"github.com/pulumi/pulumi/pkg/v3/resource/deploy/deploytest"
	pkgplugin "github.com/pulumi/pulumi/pkg/v3/resource/plugin"
	"github.com/pulumi/pulumi/pkg/v3/resource/stack"
	"github.com/pulumi/pulumi/pkg/v3/secrets"
	"github.com/pulumi/pulumi/pkg/v3/secrets/b64"
	"github.com/pulumi/pulumi/sdk/v3/go/common/diag"
	"github.com/pulumi/pulumi/sdk/v3/go/common/diag/colors"
	"github.com/pulumi/pulumi/sdk/v3/go/common/resource"
	"github.com/pulumi/pulumi/sdk/v3/go/common/resource/config"
	sdkplugin "github.com/pulumi/pulumi/sdk/v3/go/common/resource/plugin"
	"github.com/pulumi/pulumi/sdk/v3/go/common/testing/diagtest"
	"github.com/pulumi/pulumi/sdk/v3/go/common/tokens"
	"github.com/pulumi/pulumi/sdk/v3/go/common/workspace"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	pulumirpc "github.com/pulumi/pulumi/sdk/v3/proto/go"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
	"google.golang.org/protobuf/types/known/emptypb"
	"google.golang.org/protobuf/types/known/structpb"
)

const (
	importRelease = "ghcr.io/example/sub2api-deploy@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
	revisionKey   = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	hostType      = "sub2api-host:index:Host"
	hostName      = "host-edge"
	secretCanary  = "PROVIDER_IMPORT_SECRET_CANARY"
)

// TestProviderImportHelper is reached only through the test-owned SSH fixture.
// It invokes the production Runtime through the test-only construction seam.
func TestProviderImportHelper(t *testing.T) {
	if os.Getenv("SUB2API_PROVIDER_IMPORT_HELPER") != "1" {
		return
	}
	root := os.Getenv("PROVIDER_IMPORT_ROOT")
	machine := os.Getenv("PROVIDER_IMPORT_MACHINE_ID")
	digest := os.Getenv("PROVIDER_IMPORT_REQUEST_DIGEST")
	if err := testonly.ServeWithRequestDigest(os.Stdout, os.Stdin, root, machine, digest); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	os.Exit(0)
}

// TestProviderImportDockerHelper is a guarded replacement for Docker. It only
// serves the exact inspect reads generated by the preseeded Runtime fixture.
func TestProviderImportDockerHelper(t *testing.T) {
	if os.Getenv("SUB2API_PROVIDER_IMPORT_DOCKER") != "1" {
		return
	}
	if err := runDockerReadHelper(os.Args); err != nil {
		writeForbiddenDockerRecord(sanitizeDockerError(err))
		os.Exit(64)
	}
	os.Exit(0)
}

// TestEngineImportPreviewIsNoOpOrAcceptedDiff runs a real Program Import through
// the Engine, then verifies a normal program preview cannot mutate the fixture.
func TestEngineImportPreviewIsNoOpOrAcceptedDiff(t *testing.T) {
	h := newHarness(t)
	h.setupRuntime(t)

	h.resetMeasuredTrace(t)
	beforeRoot := treeManifest(t, h.provider.root)
	imported, err := h.update(t, true)
	if err != nil {
		h.mu.Lock()
		calls, operations := append([]string(nil), h.calls...), append([]pulumidisplay.StepOp(nil), h.operations...)
		h.mu.Unlock()
		t.Fatalf("Engine import update: %v (calls=%v operations=%v)", err, calls, operations)
	}
	if err := imported.VerifyIntegrity(); err != nil {
		t.Fatalf("import checkpoint integrity: %v", err)
	}
	h.assertImportResult(t, imported)
	h.assertMeasuredCalls(t, []string{"Configure", "Read", "Check", "Diff"})
	h.assertHostOperations(t, deploy.OpImport)
	h.assertLatestHostRegistration(t, "import", true)
	h.assertOneInspect(t)
	h.assertDockerReads(t, "read network-ls", "read network-ls", "read container-ls", "read app-readiness", "read container-ls", "read proxy-readiness")
	h.assertUnchangedRoot(t, beforeRoot)

	beforeSnapshot := imported
	h.resetMeasuredTrace(t)
	previewed, err := h.preview(t)
	if err != nil {
		t.Fatalf("Engine preview after import: %v", err)
	}
	if !snapshotsEqual(beforeSnapshot, previewed) {
		t.Fatal("preview changed the imported checkpoint")
	}
	h.assertMeasuredCalls(t, []string{"Configure", "Check", "Diff"})
	h.assertHostOperations(t, deploy.OpSame)
	h.assertLatestHostRegistration(t, "preview", false)
	h.assertNoEffects(t)
	h.assertDockerReads(t)
	h.assertUnchangedRoot(t, beforeRoot)
	h.assertNoCanaryLeak(t)
}

type harness struct {
	backend backend.Backend
	stack   backend.Stack
	project *workspace.Project
	root    string
	manager secrets.Manager
	key     string

	provider *providerProcess

	mu                   sync.Mutex
	calls                []string
	operations           []pulumidisplay.StepOp
	productionHostInputs resource.PropertyMap
	registrations        []hostRegistration
	phase                string
	preseededState       hostruntime.State
	capturing            bool
}

type hostRegistration struct {
	phase    string
	inputs   resource.PropertyMap
	importID string
}

func newHarness(t *testing.T) *harness {
	t.Helper()
	project := &workspace.Project{
		Name:    "sub2api-environment",
		Runtime: workspace.NewProjectRuntimeInfo("go", nil),
	}
	backendRoot := t.TempDir()
	b, err := diy.New(t.Context(), diagtest.LogSink(t), "file://"+filepath.ToSlash(backendRoot), project)
	if err != nil {
		t.Fatal(err)
	}
	ref, err := b.ParseStackReference("canary")
	if err != nil {
		t.Fatal(err)
	}
	st, err := b.CreateStack(t.Context(), ref, "", nil, nil)
	if err != nil {
		t.Fatal(err)
	}
	manager := b64.NewBase64SecretsManager()
	key, err := manager.Encrypter().EncryptValue(t.Context(), revisionKey)
	if err != nil {
		t.Fatal(err)
	}
	return &harness{
		backend: b,
		stack:   st,
		project: project,
		root:    t.TempDir(),
		manager: manager,
		key:     key,
	}
}

// setupRuntime creates a static, read-only Runtime fixture before the provider
// process exists. It intentionally never invokes Provider Create or bootstrap.
func (h *harness) setupRuntime(t *testing.T) {
	t.Helper()
	inputs := h.captureProductionInputs(t)
	fixture := writePreseed(t, inputs)
	before := treeManifest(t, fixture.root)
	validatePreseed(t, fixture)
	if after := treeManifest(t, fixture.root); !reflect.DeepEqual(before, after) {
		t.Fatal("direct Runtime inspect changed the static fixture")
	}
	h.preseededState = fixture.state
	h.provider = startProvider(t, fixture)
}

func (h *harness) resetMeasuredTrace(t *testing.T) {
	t.Helper()
	h.mu.Lock()
	h.calls = nil
	h.operations = nil
	h.mu.Unlock()

	newTraceGeneration(t, h.provider.trace)
}

func (h *harness) update(t *testing.T, importTarget bool) (*deploy.Snapshot, error) {
	return h.run(t, false, importTarget)
}

func (h *harness) preview(t *testing.T) (*deploy.Snapshot, error) {
	return h.run(t, true, false)
}

func importStackConfig(key string, importTarget bool) config.Map {
	values := config.Map{config.MustMakeKey("sub2api-host", "revisionKey"): config.NewSecureValue(key)}
	if importTarget {
		values[config.MustMakeKey("sub2api-environment", "hostImportTarget")] = config.NewValue("edge")
	}
	return values
}

func (h *harness) run(t *testing.T, preview, importTarget bool) (*deploy.Snapshot, error) {
	t.Helper()
	phase := "preview"
	if !preview && importTarget {
		phase = "import"
	} else if !preview {
		phase = "update"
	}
	h.mu.Lock()
	if h.capturing {
		h.phase = "capture"
	} else {
		h.phase = phase
	}
	h.mu.Unlock()
	runtime := newLanguageRuntime(h, importTarget)
	host := deploytest.NewPluginHostF(nil, nil, runtime, nil, nil,
		deploytest.NewProviderLoader(tokens.Package("sub2api-host"), semver.MustParse("1.0.0"), func() (pkgplugin.Provider, error) {
			return h.adapter(), nil
		}),
	)
	ctx, cancel := context.WithTimeout(t.Context(), 30*time.Second)
	defer cancel()
	op := backend.UpdateOperation{
		Proj: h.project,
		M:    &backend.UpdateMetadata{},
		Root: h.root,
		Opts: backend.UpdateOptions{
			AutoApprove: true,
			SkipPreview: !preview,
			PreviewOnly: preview,
			Display:     display.Options{Color: colors.Never, Stdout: io.Discard, Stderr: io.Discard, SuppressProgress: true},
			Engine: engine.UpdateOptions{Parallel: 1, SkipPluginPreInstall: true, HostFactory: func(context.Context, diag.Sink, diag.Sink, pkgplugin.DebugContext) (pkgplugin.Host, error) {
				return host(), nil
			}},
		},
		SecretsManager:  h.manager,
		SecretsProvider: stack.Base64SecretsProvider{},
		StackConfiguration: backend.StackConfiguration{
			Config:    importStackConfig(h.key, importTarget),
			Decrypter: h.manager.Decrypter(),
		},
		Scopes: backend.CancellationScopes,
	}
	events := make(chan engine.Event)
	done := make(chan struct{})
	var operations []pulumidisplay.StepOp
	go func() {
		defer close(done)
		for event := range events {
			if event.Type != engine.ResourcePreEvent {
				continue
			}
			metadata := event.Payload().(engine.ResourcePreEventPayload).Metadata
			if metadata.URN.Type() == hostType {
				operations = append(operations, metadata.Op)
			}
		}
	}()
	var err error
	if preview {
		_, _, err = backend.PreviewStack(ctx, h.stack, op, events)
	} else {
		_, err = h.backend.Update(ctx, h.stack, op, events)
	}
	close(events)
	<-done
	h.mu.Lock()
	h.operations = operations
	h.mu.Unlock()
	current, getErr := h.backend.GetStack(context.Background(), h.stack.Ref())
	if getErr != nil {
		t.Fatal(getErr)
	}
	snapshot, snapshotErr := current.Snapshot(context.Background(), stack.Base64SecretsProvider{})
	if snapshotErr != nil {
		t.Fatal(snapshotErr)
	}
	return snapshot, err
}

type languageRuntime struct {
	pkgplugin.LanguageRuntime
	harness      *harness
	importTarget bool
}

func newLanguageRuntime(h *harness, importTarget bool) deploytest.LanguageRuntimeFactory {
	return func() pkgplugin.LanguageRuntime {
		return &languageRuntime{
			LanguageRuntime: deploytest.NewLanguageRuntime(func(pkgplugin.RunInfo, *deploytest.ResourceMonitor) error { return nil }),
			harness:         h,
			importTarget:    importTarget,
		}
	}
}

func (r *languageRuntime) Run(ctx context.Context, info pkgplugin.RunInfo) (string, bool, error) {
	address, closeProxy, err := startMonitorProxy(ctx, info.MonitorAddress, r.harness)
	if err != nil {
		return "", false, err
	}
	defer closeProxy()
	programConfig := map[string]string{}
	for key, value := range info.Config {
		programConfig[key.String()] = value
	}
	programContext, err := pulumi.NewContext(ctx, pulumi.RunInfo{Project: info.Project, Stack: info.Stack, Parallel: info.Parallel, DryRun: info.DryRun, MonitorAddr: address, Config: programConfig})
	if err != nil {
		return "", false, err
	}
	err = errors.Join(pulumi.RunWithContext(programContext, func(c *pulumi.Context) error {
		return program.Register(c, importRelease, fixtureBytes("import.yaml"), fixtureBytes("import-secrets.yaml"))
	}), programContext.Close())
	if err != nil {
		return err.Error(), false, nil
	}
	return "", false, nil
}

type monitorProxy struct {
	pulumirpc.UnimplementedResourceMonitorServer
	upstream pulumirpc.ResourceMonitorClient
	harness  *harness
}

func startMonitorProxy(ctx context.Context, upstream string, h *harness) (string, func(), error) {
	conn, err := grpc.DialContext(ctx, upstream, grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock())
	if err != nil {
		return "", nil, err
	}
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		_ = conn.Close()
		return "", nil, err
	}
	server := grpc.NewServer()
	pulumirpc.RegisterResourceMonitorServer(server, &monitorProxy{upstream: pulumirpc.NewResourceMonitorClient(conn), harness: h})
	done := make(chan struct{})
	go func() { _ = server.Serve(listener); close(done) }()
	return listener.Addr().String(), func() {
		server.GracefulStop()
		select {
		case <-done:
		case <-time.After(time.Second):
			server.Stop()
		}
		_ = listener.Close()
		_ = conn.Close()
	}, nil
}

func (p *monitorProxy) RegisterResource(ctx context.Context, req *pulumirpc.RegisterResourceRequest) (*pulumirpc.RegisterResourceResponse, error) {
	if req.GetType() == hostType && req.GetName() == hostName {
		p.harness.mu.Lock()
		inputs := unmarshalProperties(req.GetObject())
		p.harness.registrations = append(p.harness.registrations, hostRegistration{phase: p.harness.phase, inputs: inputs.Copy(), importID: req.GetImportId()})
		if p.harness.phase == "capture" && p.harness.productionHostInputs == nil {
			p.harness.productionHostInputs = inputs
		}
		p.harness.mu.Unlock()
	}
	return p.upstream.RegisterResource(ctx, req)
}

func (p *monitorProxy) SupportsFeature(c context.Context, r *pulumirpc.SupportsFeatureRequest) (*pulumirpc.SupportsFeatureResponse, error) {
	return p.upstream.SupportsFeature(c, r)
}
func (p *monitorProxy) RegisterResourceOutputs(c context.Context, r *pulumirpc.RegisterResourceOutputsRequest) (*emptypb.Empty, error) {
	return p.upstream.RegisterResourceOutputs(c, r)
}
func (p *monitorProxy) GetDeploymentInfo(c context.Context, r *emptypb.Empty) (*pulumirpc.DeploymentInfo, error) {
	return p.upstream.GetDeploymentInfo(c, r)
}
func (p *monitorProxy) Invoke(c context.Context, r *pulumirpc.ResourceInvokeRequest) (*pulumirpc.ResourceInvokeResponse, error) {
	return p.upstream.Invoke(c, r)
}
func (p *monitorProxy) Call(c context.Context, r *pulumirpc.ResourceCallRequest) (*pulumirpc.CallResponse, error) {
	return p.upstream.Call(c, r)
}
func (p *monitorProxy) ReadResource(c context.Context, r *pulumirpc.ReadResourceRequest) (*pulumirpc.ReadResourceResponse, error) {
	return p.upstream.ReadResource(c, r)
}
func (p *monitorProxy) RegisterStackTransform(c context.Context, r *pulumirpc.Callback) (*emptypb.Empty, error) {
	return p.upstream.RegisterStackTransform(c, r)
}
func (p *monitorProxy) RegisterStackInvokeTransform(c context.Context, r *pulumirpc.Callback) (*emptypb.Empty, error) {
	return p.upstream.RegisterStackInvokeTransform(c, r)
}
func (p *monitorProxy) RegisterResourceHook(c context.Context, r *pulumirpc.RegisterResourceHookRequest) (*emptypb.Empty, error) {
	return p.upstream.RegisterResourceHook(c, r)
}
func (p *monitorProxy) RegisterErrorHook(c context.Context, r *pulumirpc.RegisterErrorHookRequest) (*emptypb.Empty, error) {
	return p.upstream.RegisterErrorHook(c, r)
}
func (p *monitorProxy) RegisterPackage(c context.Context, r *pulumirpc.RegisterPackageRequest) (*pulumirpc.RegisterPackageResponse, error) {
	return p.upstream.RegisterPackage(c, r)
}
func (p *monitorProxy) SignalAndWaitForShutdown(c context.Context, r *emptypb.Empty) (*emptypb.Empty, error) {
	return p.upstream.SignalAndWaitForShutdown(c, r)
}

func (h *harness) adapter() pkgplugin.Provider {
	return &deploytest.Provider{
		ConfigureF: func(ctx context.Context, req pkgplugin.ConfigureRequest) (pkgplugin.ConfigureResponse, error) {
			if h.isCapturing() {
				return pkgplugin.ConfigureResponse{}, nil
			}
			h.record("Configure")
			_, err := h.provider.client.Configure(ctx, &pulumirpc.ConfigureRequest{Args: marshalProperties(nil, req.Inputs)})
			return pkgplugin.ConfigureResponse{}, err
		},
		CheckF: func(ctx context.Context, req pkgplugin.CheckRequest) (pkgplugin.CheckResponse, error) {
			if h.isCapturing() {
				return pkgplugin.CheckResponse{Properties: req.News}, nil
			}
			h.record("Check")
			response, err := h.provider.client.Check(ctx, &pulumirpc.CheckRequest{Urn: string(req.URN), Olds: marshalProperties(nil, req.Olds), News: marshalProperties(nil, req.News)})
			if err != nil {
				return pkgplugin.CheckResponse{}, err
			}
			return pkgplugin.CheckResponse{Properties: unmarshalProperties(response.Inputs)}, nil
		},
		DiffF: func(ctx context.Context, req pkgplugin.DiffRequest) (pkgplugin.DiffResult, error) {
			if h.isCapturing() {
				return pkgplugin.DiffResult{Changes: pkgplugin.DiffNone}, nil
			}
			h.record("Diff")
			response, err := h.provider.client.Diff(ctx, &pulumirpc.DiffRequest{Id: string(req.ID), Urn: string(req.URN), Olds: marshalProperties(nil, req.OldOutputs), OldInputs: marshalProperties(nil, req.OldInputs), News: marshalProperties(nil, req.NewInputs)})
			if err != nil {
				return pkgplugin.DiffResult{}, err
			}
			if importOmittedEmptyCollections(req, response) {
				return pkgplugin.DiffResult{Changes: pkgplugin.DiffNone}, nil
			}
			if response.Changes == pulumirpc.DiffResponse_DIFF_NONE {
				return pkgplugin.DiffResult{Changes: pkgplugin.DiffNone}, nil
			}
			return pkgplugin.DiffResult{Changes: pkgplugin.DiffSome}, nil
		},
		ReadF: func(ctx context.Context, req pkgplugin.ReadRequest) (pkgplugin.ReadResponse, error) {
			if h.isCapturing() {
				return pkgplugin.ReadResponse{}, errors.New("capture preview unexpectedly read Host")
			}
			h.record("Read")
			response, err := h.provider.client.Read(ctx, &pulumirpc.ReadRequest{Id: string(req.ID), Urn: string(req.URN), Name: req.Name, Type: string(req.Type), Inputs: marshalProperties(nil, req.Inputs), Properties: marshalProperties(nil, req.State)})
			if err != nil {
				return pkgplugin.ReadResponse{}, err
			}
			return pkgplugin.ReadResponse{ReadResult: pkgplugin.ReadResult{ID: resource.ID(response.Id), Inputs: unmarshalProperties(response.Inputs), Outputs: unmarshalProperties(response.Properties)}}, nil
		},
		CreateF: func(ctx context.Context, req pkgplugin.CreateRequest) (pkgplugin.CreateResponse, error) {
			h.mu.Lock()
			capturing := h.capturing
			h.mu.Unlock()
			if capturing {
				return pkgplugin.CreateResponse{ID: resource.ID(h.stableID()), Properties: req.Properties, Status: resource.StatusOK}, nil
			}
			return forbiddenCreate(h)(ctx, req)
		},
		UpdateF: forbiddenUpdate(h),
		DeleteF: forbiddenDelete(h),
	}
}

func (h *harness) record(call string) {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.calls = append(h.calls, call)
}

// Import tokens encode Go structs, where empty collections are omitted. The
// normal program registration retains its empty Pulumi containers. This is the
// sole accepted representation-only import difference; every other provider
// diff remains visible to the Engine.
func importOmittedEmptyCollections(req pkgplugin.DiffRequest, response *pulumirpc.DiffResponse) bool {
	if response.Changes != pulumirpc.DiffResponse_DIFF_SOME || len(response.Replaces) != 0 || len(response.Diffs) != 2 || !containsDiff(response.Diffs, "target") || !containsDiff(response.Diffs, "secrets") {
		return false
	}
	oldTarget, targetOK := req.OldInputs["target"]
	oldSecrets, secretsOK := req.OldInputs["secrets"]
	newTarget, newTargetOK := req.NewInputs["target"]
	newSecrets, newSecretsOK := req.NewInputs["secrets"]
	if !targetOK || !secretsOK || !newTargetOK || !newSecretsOK {
		return false
	}
	var oldTargetValue, newTargetValue hostcontract.Target
	var oldSecretValues, newSecretValues hostcontract.Secrets
	if !decodePropertyJSON(oldTarget, &oldTargetValue) || !decodePropertyJSON(newTarget, &newTargetValue) || !decodePropertyJSON(oldSecrets, &oldSecretValues) || !decodePropertyJSON(newSecrets, &newSecretValues) {
		return false
	}
	oldTargetValue, oldSecretValues = hostcontract.NormalizeTargetSecrets(oldTargetValue, oldSecretValues)
	newTargetValue, newSecretValues = hostcontract.NormalizeTargetSecrets(newTargetValue, newSecretValues)
	return reflect.DeepEqual(oldTargetValue, newTargetValue) && reflect.DeepEqual(oldSecretValues, newSecretValues)
}

func containsDiff(diffs []string, want string) bool {
	for _, diff := range diffs {
		if diff == want {
			return true
		}
	}
	return false
}

func decodePropertyJSON(value resource.PropertyValue, into any) bool {
	b, err := json.Marshal(unwrapFixtureValue(value).Mappable())
	return err == nil && json.Unmarshal(b, into) == nil
}
func (h *harness) isCapturing() bool { h.mu.Lock(); defer h.mu.Unlock(); return h.capturing }
func forbiddenCreate(h *harness) func(context.Context, pkgplugin.CreateRequest) (pkgplugin.CreateResponse, error) {
	return func(context.Context, pkgplugin.CreateRequest) (pkgplugin.CreateResponse, error) {
		h.record("Create")
		return pkgplugin.CreateResponse{}, errors.New("unexpected Engine Create")
	}
}
func forbiddenUpdate(h *harness) func(context.Context, pkgplugin.UpdateRequest) (pkgplugin.UpdateResponse, error) {
	return func(_ context.Context, req pkgplugin.UpdateRequest) (pkgplugin.UpdateResponse, error) {
		h.record("Update")
		return pkgplugin.UpdateResponse{}, fmt.Errorf("unexpected Engine Update for %s (%s)", req.URN, req.ID)
	}
}
func forbiddenDelete(h *harness) func(context.Context, pkgplugin.DeleteRequest) (pkgplugin.DeleteResponse, error) {
	return func(context.Context, pkgplugin.DeleteRequest) (pkgplugin.DeleteResponse, error) {
		h.record("Delete")
		return pkgplugin.DeleteResponse{}, errors.New("unexpected Engine Delete")
	}
}

type providerProcess struct {
	cmd         *exec.Cmd
	client      pulumirpc.ResourceProviderClient
	conn        *grpc.ClientConn
	stdout      io.ReadCloser
	stderr      *lockedBuffer
	done        <-chan error
	identity    processIdentity
	root, trace string
}
type lockedBuffer struct {
	mu  sync.Mutex
	buf bytes.Buffer
}

func (b *lockedBuffer) Write(value []byte) (int, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.Write(value)
}
func (b *lockedBuffer) String() string {
	b.mu.Lock()
	defer b.mu.Unlock()
	return b.buf.String()
}

type processIdentity struct {
	pid   int
	start string
}

type preseedFixture struct {
	root, machine, trace string
	model                dockerReadModel
	state                hostruntime.State
}

type dockerReadModel struct {
	NetworkName  string                     `json:"networkName"`
	NetworkOwner string                     `json:"networkOwner"`
	NetworkLabel string                     `json:"networkLabel"`
	Containers   map[string]dockerContainer `json:"containers"`
}

type dockerContainer struct {
	Owner         string `json:"owner"`
	Target        string `json:"target"`
	ReadinessPath string `json:"readinessPath"`
}

type fixtureInventory struct {
	Version         int                            `json:"version"`
	Resource        hostcontract.ResourceIdentity  `json:"resource"`
	Ownership       hostcontract.OwnershipIdentity `json:"ownership"`
	AppliedRevision string                         `json:"appliedRevision"`
	Objects         []fixtureManagedObject         `json:"objects"`
}

// fixtureManagedObject mirrors only hostruntime's private JSON inventory schema.
// It is fixture data, never a production replacement for that private type.
type fixtureManagedObject struct {
	Role          string                    `json:"role"`
	AppToken      string                    `json:"appToken,omitempty"`
	Name          string                    `json:"name"`
	Image         string                    `json:"image,omitempty"`
	Data          []fixtureManagedLink      `json:"data,omitempty"`
	Revision      string                    `json:"revision,omitempty"`
	Active        string                    `json:"active,omitempty"`
	Env           string                    `json:"env,omitempty"`
	Type          string                    `json:"type,omitempty"`
	Port          int                       `json:"port,omitempty"`
	Persistence   bool                      `json:"persistence,omitempty"`
	DataToken     string                    `json:"dataToken,omitempty"`
	PathToken     string                    `json:"pathToken,omitempty"`
	DataIdentity  hostcontract.DataIdentity `json:"dataIdentity,omitempty"`
	Config        string                    `json:"config,omitempty"`
	Hostname      string                    `json:"hostname,omitempty"`
	ReadinessPath string                    `json:"readinessPath,omitempty"`
	DrainSeconds  int                       `json:"drainSeconds,omitempty"`
}

type fixtureManagedLink struct {
	Name     string                    `json:"name"`
	Identity hostcontract.DataIdentity `json:"identity"`
}

type fixtureRouteDocument struct {
	HTTP fixtureRouteHTTP `json:"http"`
}
type fixtureRouteHTTP struct {
	Routers  map[string]fixtureRouter  `json:"routers"`
	Services map[string]fixtureService `json:"services"`
}
type fixtureRouter struct {
	Rule        string      `json:"rule"`
	EntryPoints []string    `json:"entryPoints"`
	Service     string      `json:"service"`
	TLS         *fixtureTLS `json:"tls,omitempty"`
}
type fixtureTLS struct {
	CertResolver string `json:"certResolver"`
}
type fixtureService struct {
	LoadBalancer fixtureLoadBalancer `json:"loadBalancer"`
}
type fixtureLoadBalancer struct {
	Servers []fixtureServer `json:"servers"`
}
type fixtureServer struct {
	URL string `json:"url"`
}

func writePreseed(t *testing.T, inputs resource.PropertyMap) preseedFixture {
	t.Helper()
	caseDir := t.TempDir()
	root := filepath.Join(caseDir, "state")
	trace := filepath.Join(caseDir, "trace")
	machinePath := filepath.Join(caseDir, "machine-id")
	for _, path := range []string{root, trace, filepath.Join(root, "runtime", "managed"), filepath.Join(root, "runtime", "dynamic"), filepath.Join(root, "runtime", "data")} {
		if err := os.MkdirAll(path, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	bin := filepath.Join(caseDir, "bin")
	if err := os.MkdirAll(bin, 0o700); err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(bin, "docker"), dockerShim(), 0o700)
	t.Setenv("PATH", bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	t.Setenv("PROVIDER_IMPORT_TRACE", trace)
	t.Setenv("PROVIDER_IMPORT_TEST_BINARY", os.Args[0])
	t.Setenv("PROVIDER_IMPORT_DOCKER_MODEL", filepath.Join(trace, "docker-model.json"))
	writeFixture(t, machinePath, []byte("0123456789abcdef0123456789abcdef\n"), 0o600)
	resourceValue, target, secretValues := decodeFixtureInputs(t, inputs)
	machine := fixtureMachineIdentity()
	ownership := hostcontract.OwnershipIdentity{Value: "oid1:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"}
	revision := fixtureRevision(t, resourceValue, target, secretValues)
	writeFixture(t, filepath.Join(bin, "nft"), nftShim(fixtureNftTableName(resourceValue, ownership)), 0o700)
	appToken := fixtureToken("app", "app")
	appName := fixtureObjectName(resourceValue, ownership, "app", appToken, "green")
	proxyName := fixtureObjectName(resourceValue, ownership, "proxy", "proxy", "live")
	appEnv := "env-" + appToken + fixtureToken(revision)
	proxyToken := fixtureToken("proxy")
	proxyEnv := "env-" + proxyToken + fixtureToken(revision)
	proxyConfig := "config-" + fixtureToken("proxy", revision)
	app := target.Apps[0]
	inventory := fixtureInventory{Version: 3, Resource: resourceValue, Ownership: ownership, AppliedRevision: revision, Objects: []fixtureManagedObject{
		{Role: "app", AppToken: appToken, Name: appName, Image: app.Image, Data: fixtureLinks(app.DataLinks), Revision: revision, Active: "green", Env: appEnv, Hostname: app.Hostname, ReadinessPath: app.ReadinessPath, DrainSeconds: 30},
		{Role: "proxy", Name: proxyName, Image: target.ReverseProxy.Image, Revision: revision, Env: proxyEnv, Config: proxyConfig},
	}}
	writeJSONFixture(t, filepath.Join(root, "runtime", "managed", "inventory.json"), inventory, 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", appEnv), fixtureAppEnv(secretValues), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", proxyEnv), []byte("CF_DNS_API_TOKEN="+secretValues.ReverseProxy.DNSChallengeToken+"\n"), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "managed", proxyConfig), fixtureProxyConfig(target.ReverseProxy.ACMEEmail), 0o600)
	dataDir := filepath.Join(root, "runtime", "data", fixtureToken("app-data", appToken))
	if err := os.MkdirAll(dataDir, 0o700); err != nil {
		t.Fatal(err)
	}
	writeFixture(t, filepath.Join(dataDir, "sentinel"), []byte("persistent-data-sentinel\n"), 0o600)
	writeFixture(t, filepath.Join(root, "runtime", "dynamic", "route-"+appToken+".json"), fixtureRoute(resourceValue, ownership, appToken, appName, revision, app.Hostname), 0o600)
	observation := hostcontract.StableObservation{Machine: machine, Ownership: ownership, HostRelease: target.ReleaseArtifact, AppliedRevision: revision, Ready: true, Apps: []hostcontract.AppObservation{{ID: app.ID, ActiveImage: app.Image, Ready: true}}}
	state := hostruntime.State{Version: 1, Resource: resourceValue, Machine: machine, Ownership: ownership, AppliedRevision: revision, Observation: observation}
	writeJSONFixture(t, filepath.Join(root, "state.json"), state, 0o600)
	model := dockerReadModel{NetworkName: fixtureNetworkName(resourceValue, ownership), NetworkOwner: fixtureOwnershipLabel(resourceValue, ownership, "network", "", ""), NetworkLabel: fixtureNetworkLabel(resourceValue, ownership), Containers: map[string]dockerContainer{
		appName:   {Owner: fixtureOwnershipLabel(resourceValue, ownership, "app", appToken, "green"), Target: fixtureTargetLabel("app", appToken, "green", revision, app.Image), ReadinessPath: app.ReadinessPath},
		proxyName: {Owner: fixtureOwnershipLabel(resourceValue, ownership, "proxy", "", ""), Target: fixtureTargetLabel("proxy", "", "", revision, target.ReverseProxy.Image), ReadinessPath: ""},
	}}
	writeJSONFixture(t, filepath.Join(trace, "docker-model.json"), model, 0o600)
	newTraceGeneration(t, trace)
	return preseedFixture{root: root, machine: machinePath, trace: trace, model: model, state: state}
}

func validatePreseed(t *testing.T, fixture preseedFixture) {
	t.Helper()
	request := hostprotocol.Request{Action: hostcontract.ActionInspect, Server: hostcontract.ServerTarget{SSHAlias: "edge"}, Resource: hostcontract.ResourceIdentity{Environment: "canary", ServerKey: "edge"}, TargetRevision: readFixtureRevision(t, fixture.root)}
	frame, err := hostprotocol.EncodeRequest(request)
	if err != nil {
		t.Fatal(err)
	}
	var response bytes.Buffer
	digest := filepath.Join(fixture.trace, "preseed.digest")
	if err := testonly.ServeWithRequestDigest(&response, bytes.NewReader(frame), fixture.root, fixture.machine, digest); err != nil {
		t.Fatalf("direct preseed inspect: %v", err)
	}
	decoded, err := hostprotocol.DecodeResponse(response.Bytes())
	if err != nil || decoded.Result == nil || decoded.Result.Observation == nil || !decoded.Result.Observation.Ready || decoded.Result.Observation.Drifted {
		var errorCategory hostprotocol.ErrorCategory
		var errorCode hostprotocol.ErrorCode
		if decoded.Error != nil {
			errorCategory = decoded.Error.Category
			errorCode = decoded.Error.Code
		}
		t.Fatalf("direct preseed inspect did not return a ready observation: category=preseed-inspect error-category=%q error-code=%q", errorCategory, errorCode)
	}
}

func readTraceFile(trace, name string) string {
	b, _ := os.ReadFile(filepath.Join(trace, "current", name))
	return string(b)
}

func decodeFixtureInputs(t *testing.T, inputs resource.PropertyMap) (hostcontract.ResourceIdentity, hostcontract.Target, hostcontract.Secrets) {
	t.Helper()
	var resourceValue hostcontract.ResourceIdentity
	var target hostcontract.Target
	var secretValues hostcontract.Secrets
	decode := func(name string, into any) {
		b, err := json.Marshal(unwrapFixtureValue(inputs[resource.PropertyKey(name)]).Mappable())
		if err != nil {
			t.Fatal(err)
		}
		if err = json.Unmarshal(b, into); err != nil {
			t.Fatal(err)
		}
	}
	decode("resource", &resourceValue)
	decode("target", &target)
	decode("secrets", &secretValues)
	if resourceValue != (hostcontract.ResourceIdentity{Environment: "canary", ServerKey: "edge"}) || len(target.Apps) != 1 || target.ReverseProxy == nil {
		t.Fatal("unexpected import fixture shape")
	}
	return resourceValue, target, secretValues
}

func unwrapFixtureValue(value resource.PropertyValue) resource.PropertyValue {
	for value.IsSecret() {
		value = value.SecretValue().Element
	}
	return value
}

func fixtureMachineIdentity() hostcontract.MachineIdentity {
	return hostcontract.MachineIdentity{Value: "mid1:0911601b3b0a5f6fdc51f3661518ee20e26ea0cbadfb4f7283e5b1f288941f54"}
}
func fixtureRevision(t *testing.T, resourceValue hostcontract.ResourceIdentity, target hostcontract.Target, secretValues hostcontract.Secrets) string {
	t.Helper()
	key, err := base64.StdEncoding.DecodeString(revisionKey)
	if err != nil {
		t.Fatal(err)
	}
	revision, err := hostcontract.TargetRevision(hostcontract.RevisionKey(key), resourceValue, target, secretValues)
	if err != nil {
		t.Fatalf("fixture target revision: %v (validation=%v)", err, hostcontract.ValidateTarget(target, secretValues))
	}
	return revision
}
func fixtureLinks(links []hostcontract.DataLink) []fixtureManagedLink {
	out := make([]fixtureManagedLink, len(links))
	for i, link := range links {
		out[i] = fixtureManagedLink{Name: link.Name, Identity: link.Identity}
	}
	return out
}
func fixtureToken(values ...string) string {
	h := sha256.New()
	for _, value := range values {
		_, _ = h.Write([]byte(value))
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil)[:12])
}
func fixtureObjectName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, role, app, slot string) string {
	return "s2h-" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value, role, app, slot)
}
func fixtureOwnershipLabel(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, role, app, slot string) string {
	return "s2h1:" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value, role, app, slot)
}
func fixtureTargetLabel(role, app, active, revision, image string) string {
	return "s2ht1:" + fixtureToken(role, app, active, revision, image, "", "0", "false")
}
func fixtureNetworkName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2h-net-" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureNftTableName(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2h_" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureNetworkLabel(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity) string {
	return "s2hnet1:" + fixtureToken(resourceValue.Environment, resourceValue.ServerKey, ownership.Value)
}
func fixtureAppEnv(secrets hostcontract.Secrets) []byte {
	app := secrets.Apps["app"]
	return []byte("ADMIN_EMAIL=admin@example.test\nFEATURE_FLAG=enabled\nINITIAL_ADMIN_PASSWORD=" + app.InitialAdminPassword + "\nJWT_SECRET=" + app.JWTSecret + "\nTOTP_ENCRYPTION_KEY=" + app.TOTPEncryptionKey + "\nPOSTGRES_USERNAME=" + app.Postgres.Username + "\nPOSTGRES_PASSWORD=" + app.Postgres.Password + "\nREDIS_USERNAME=" + app.Redis.Username + "\nREDIS_PASSWORD=" + app.Redis.Password + "\n")
}
func fixtureProxyConfig(email string) []byte {
	return []byte("entryPoints:\n  web:\n    address: \":80\"\n  websecure:\n    address: \":443\"\n  probe:\n    address: \":8081\"\nproviders:\n  file:\n    directory: /etc/traefik/dynamic\n    watch: true\ncertificatesResolvers:\n  cloudflare:\n    acme:\n      email: " + strconv.Quote(email) + "\n      storage: /etc/traefik/acme.json\n      dnsChallenge:\n        provider: cloudflare\n")
}
func fixtureRoute(resourceValue hostcontract.ResourceIdentity, ownership hostcontract.OwnershipIdentity, token, name, revision, hostname string) []byte {
	key := fixtureToken("route", resourceValue.Environment, resourceValue.ServerKey, ownership.Value, token, revision, "green", name)
	service := fixtureToken("service", key)
	route := fixtureRouteDocument{HTTP: fixtureRouteHTTP{
		Routers: map[string]fixtureRouter{
			fixtureToken("router", "public", key): {Rule: "Host(`" + hostname + "`)", EntryPoints: []string{"websecure"}, Service: service, TLS: &fixtureTLS{CertResolver: "cloudflare"}},
			fixtureToken("router", "probe", key):  {Rule: "Host(`" + hostname + "`)", EntryPoints: []string{"probe"}, Service: service},
		},
		Services: map[string]fixtureService{service: {LoadBalancer: fixtureLoadBalancer{Servers: []fixtureServer{{URL: "http://" + name + ":8080"}}}}},
	}}
	b, _ := json.Marshal(route)
	return b
}
func readFixtureRevision(t *testing.T, root string) string {
	t.Helper()
	var state hostruntime.State
	b, err := os.ReadFile(filepath.Join(root, "state.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err = json.Unmarshal(b, &state); err != nil {
		t.Fatal(err)
	}
	return state.AppliedRevision
}
func writeJSONFixture(t *testing.T, path string, value any, mode os.FileMode) {
	t.Helper()
	b, err := json.Marshal(value)
	if err != nil {
		t.Fatal(err)
	}
	writeFixture(t, path, b, mode)
}

func dockerShim() []byte {
	return []byte("#!/bin/sh\nexec env SUB2API_PROVIDER_IMPORT_DOCKER=1 \"$PROVIDER_IMPORT_TEST_BINARY\" -test.run '^TestProviderImportDockerHelper$' -- \"$@\"\n")
}

func nftShim(table string) []byte {
	return []byte("#!/bin/sh\nif [ \"$#\" -eq 5 ] && [ \"$1\" = \"-j\" ] && [ \"$2\" = \"list\" ] && [ \"$3\" = \"table\" ] && [ \"$4\" = \"inet\" ] && [ \"$5\" = \"" + table + "\" ]; then\n  printf '%s\\n' 'Error: No such file or directory' >&2\n  exit 1\nfi\nprintf '%s\\n' 'unsupported nft invocation' >&2\nexit 64\n")
}

func runDockerReadHelper(argv []string) error {
	separator := -1
	for i, value := range argv {
		if value == "--" {
			separator = i
			break
		}
	}
	if separator < 0 || separator == len(argv)-1 {
		return errors.New("missing docker arguments")
	}
	var model dockerReadModel
	b, err := os.ReadFile(os.Getenv("PROVIDER_IMPORT_DOCKER_MODEL"))
	if err != nil || json.Unmarshal(b, &model) != nil {
		return errors.New("invalid docker model")
	}
	args := argv[separator+1:]
	network := []string{"network", "ls", "--filter", "name=^" + model.NetworkName + "$", "--format", "{{.Name}}\t{{index .Labels \"sub2api.host\"}}\t{{index .Labels \"sub2api.host.network\"}}"}
	if reflect.DeepEqual(args, network) {
		_, err = fmt.Fprintf(os.Stdout, "%s\t%s\t%s\n", model.NetworkName, model.NetworkOwner, model.NetworkLabel)
		if err == nil {
			writeDockerRecord("read network-ls")
		}
		return err
	}
	if len(args) == 7 && args[0] == "container" && args[1] == "ls" && args[2] == "--all" && args[3] == "--filter" && strings.HasPrefix(args[4], "name=^/") && strings.HasSuffix(args[4], "$") && args[5] == "--format" && args[6] == "{{.Names}}\t{{index .Labels \"sub2api.host\"}}\t{{index .Labels \"sub2api.host.target\"}}" {
		name := strings.TrimSuffix(strings.TrimPrefix(args[4], "name=^/"), "$")
		container, ok := model.Containers[name]
		if !ok {
			return errors.New("unknown inspect container")
		}
		_, err = fmt.Fprintf(os.Stdout, "%s\t%s\t%s\n", name, container.Owner, container.Target)
		if err == nil {
			writeDockerRecord("read container-ls")
		}
		return err
	}
	if len(args) == 7 && args[0] == "exec" && args[2] == "wget" && args[3] == "-q" && args[4] == "-O" && args[5] == "/dev/null" {
		container, ok := model.Containers[args[1]]
		if !ok || args[6] != "http://localhost:8080"+container.ReadinessPath {
			return errors.New("invalid app readiness")
		}
		writeDockerRecord("read app-readiness")
		return nil
	}
	if len(args) == 4 && args[0] == "exec" && args[2] == "traefik" && args[3] == "version" {
		container, ok := model.Containers[args[1]]
		if !ok || container.ReadinessPath != "" {
			return errors.New("invalid proxy readiness")
		}
		writeDockerRecord("read proxy-readiness")
		return nil
	}
	return errors.New("forbidden docker mutation or unsupported read")
}

func writeDockerRecord(record string) {
	trace := os.Getenv("PROVIDER_IMPORT_TRACE")
	file, err := os.OpenFile(filepath.Join(trace, "current", "docker-reads"), os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		return
	}
	defer file.Close()
	_, _ = file.WriteString(record + "\n")
}

func writeForbiddenDockerRecord(record string) {
	trace := os.Getenv("PROVIDER_IMPORT_TRACE")
	path := filepath.Join(trace, "current", "forbidden")
	_ = os.WriteFile(path, []byte(record+"\n"), 0o600)
}

func sanitizeDockerError(err error) string {
	return strings.NewReplacer("\n", " ", "\r", " ", "\x00", " ").Replace(err.Error())
}

func newTraceGeneration(t *testing.T, trace string) {
	t.Helper()
	name := fmt.Sprintf("%d-%s", time.Now().UnixNano(), fixtureToken(t.Name()))
	if err := os.MkdirAll(filepath.Join(trace, "generations", name), 0o700); err != nil {
		t.Fatal(err)
	}
	temporary := filepath.Join(trace, ".current-"+name)
	if err := os.Symlink(filepath.Join("generations", name), temporary); err != nil {
		t.Fatal(err)
	}
	if err := os.Rename(temporary, filepath.Join(trace, "current")); err != nil {
		t.Fatal(err)
	}
}

func startProvider(t *testing.T, fixture preseedFixture) *providerProcess {
	t.Helper()
	caseDir := filepath.Dir(fixture.root)
	bin := filepath.Join(caseDir, "bin")
	for _, path := range []string{bin, filepath.Join(caseDir, "release", "bin")} {
		if err := os.MkdirAll(path, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	writeFixture(t, filepath.Join(bin, "ssh"), fixtureFile(t, "ssh-import.sh"), 0o700)
	writeFixture(t, filepath.Join(bin, "docker"), dockerShim(), 0o700)
	providerDir := filepath.Join(caseDir, "release", "bin")
	binary := filepath.Join(providerDir, "pulumi-resource-sub2api-host")
	buildContext, cancel := context.WithTimeout(t.Context(), 30*time.Second)
	defer cancel()
	build := exec.CommandContext(buildContext, "go", "build", "-o", binary, "./cmd/pulumi-resource-sub2api-host")
	build.Dir = repositoryRoot(t)
	if output, err := build.CombinedOutput(); err != nil {
		t.Fatalf("build provider: %v: %s", err, output)
	}
	cmd := exec.Command(binary)
	cmd.Dir = repositoryRoot(t)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	cmd.Env = append(os.Environ(),
		"PATH="+bin+string(os.PathListSeparator)+os.Getenv("PATH"),
		"PROVIDER_IMPORT_TRACE="+fixture.trace,
		"PROVIDER_IMPORT_ROOT="+fixture.root,
		"PROVIDER_IMPORT_MACHINE_ID="+fixture.machine,
		"PROVIDER_IMPORT_TEST_BINARY="+os.Args[0],
		"PROVIDER_IMPORT_REQUEST_DIGEST="+filepath.Join(fixture.trace, "current", "request.digest"),
		"PROVIDER_IMPORT_DOCKER_MODEL="+filepath.Join(fixture.trace, "docker-model.json"),
	)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		t.Fatal(err)
	}
	stderr := &lockedBuffer{}
	cmd.Stderr = stderr
	if err = cmd.Start(); err != nil {
		t.Fatal(err)
	}
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()
	identity := processIdentity{pid: cmd.Process.Pid, start: processStart(cmd.Process.Pid)}
	port := readPort(t, stdout)
	ctx, cancelDial := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancelDial()
	conn, err := grpc.DialContext(ctx, net.JoinHostPort("127.0.0.1", port), grpc.WithTransportCredentials(insecure.NewCredentials()), grpc.WithBlock())
	if err != nil {
		t.Fatal(err)
	}
	p := &providerProcess{cmd: cmd, client: pulumirpc.NewResourceProviderClient(conn), conn: conn, stdout: stdout, stderr: stderr, done: done, identity: identity, root: fixture.root, trace: fixture.trace}
	t.Cleanup(func() { _ = conn.Close(); _ = stdout.Close(); stopProvider(t, p) })
	ctx, cancelConfigure := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancelConfigure()
	if _, err := p.client.Configure(ctx, &pulumirpc.ConfigureRequest{Args: marshalProperties(t, resource.PropertyMap{"revisionKey": resource.MakeSecret(resource.NewStringProperty(revisionKey))})}); err != nil {
		t.Fatal(err)
	}
	return p
}

func (h *harness) captureProductionInputs(t *testing.T) resource.PropertyMap {
	h.productionHostInputs = nil
	h.mu.Lock()
	h.capturing = true
	h.phase = "capture"
	h.mu.Unlock()
	defer func() {
		h.mu.Lock()
		h.capturing = false
		h.mu.Unlock()
	}()
	_, err := h.run(t, true, false)
	if err != nil {
		t.Fatalf("capture production inputs: %v", err)
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.productionHostInputs == nil {
		t.Fatal("program did not register Host")
	}
	if len(h.registrations) != 1 || h.registrations[0].phase != "capture" || h.registrations[0].importID != "" {
		t.Fatal("normal Program registration unexpectedly imported Host")
	}
	return h.productionHostInputs.Copy()
}
func (h *harness) stableID() string {
	sum := sha256.Sum256([]byte("sub2api-host-resource-id-v1:6:canary4:edge"))
	return "host-" + hex.EncodeToString(sum[:])
}
func (h *harness) assertImportResult(t *testing.T, snapshot *deploy.Snapshot) {
	state := singleHost(t, snapshot)
	h.mu.Lock()
	var token string
	for _, registration := range h.registrations {
		if registration.phase == "import" {
			token = registration.importID
		}
	}
	preseeded := h.preseededState
	h.mu.Unlock()
	if string(state.URN) != hostURN() {
		t.Fatalf("Host URN = %q, want %q", state.URN, hostURN())
	}
	if !strings.HasPrefix(token, "hit1:") || state.ID != resource.ID(h.stableID()) || state.ImportID != resource.ID(token) {
		t.Fatalf("Host state did not preserve real encrypted import token")
	}
	assertCanonicalHostInputs(t, state.Inputs, h.productionHostInputs)
	assertImportedCheckpoint(t, state, preseeded)
	if !secretOnlyProperty(state.Outputs, secretCanary, false) {
		t.Fatal("import checkpoint exposes the secret canary outside a secret property")
	}
}
func (h *harness) assertLatestHostRegistration(t *testing.T, phase string, imported bool) {
	t.Helper()
	h.mu.Lock()
	defer h.mu.Unlock()
	for index := len(h.registrations) - 1; index >= 0; index-- {
		registration := h.registrations[index]
		if registration.phase != phase {
			continue
		}
		if imported && !strings.HasPrefix(registration.importID, "hit1:") {
			t.Fatalf("%s Host registration ImportId = %q, want hit1 token", phase, registration.importID)
		}
		if !imported && registration.importID != "" {
			t.Fatalf("%s Host registration ImportId = %q, want empty", phase, registration.importID)
		}
		return
	}
	t.Fatalf("no Host registration recorded for %s", phase)
}
func assertImportedCheckpoint(t *testing.T, state *pkgresource.State, expected hostruntime.State) {
	t.Helper()
	var machine hostcontract.MachineIdentity
	var ownership hostcontract.OwnershipIdentity
	var revision string
	var observation hostcontract.StableObservation
	for _, item := range []struct {
		name string
		into any
	}{{"machine", &machine}, {"ownership", &ownership}, {"appliedRevision", &revision}, {"observation", &observation}} {
		value, ok := state.Outputs[resource.PropertyKey(item.name)]
		if !ok || value.ContainsSecrets() || value.IsComputed() || !decodePropertyJSON(value, item.into) {
			t.Fatalf("import checkpoint output %s is missing, secret, unknown, or invalid", item.name)
		}
	}
	if machine != expected.Machine || ownership != expected.Ownership || revision != expected.AppliedRevision || !reflect.DeepEqual(observation, expected.Observation) {
		t.Fatal("import checkpoint outputs differ from preseeded Runtime state")
	}
}
func secretOnlyProperty(values resource.PropertyMap, canary string, secret bool) bool {
	for _, value := range values {
		if !secretOnlyValue(value, canary, secret) {
			return false
		}
	}
	return true
}
func secretOnlyValue(value resource.PropertyValue, canary string, secret bool) bool {
	if value.IsSecret() {
		return secretOnlyValue(value.SecretValue().Element, canary, true)
	}
	if value.IsString() {
		return !strings.Contains(value.StringValue(), canary) || secret
	}
	if value.IsArray() {
		for _, child := range value.ArrayValue() {
			if !secretOnlyValue(child, canary, secret) {
				return false
			}
		}
	}
	if value.IsObject() {
		for _, child := range value.ObjectValue() {
			if !secretOnlyValue(child, canary, secret) {
				return false
			}
		}
	}
	return true
}
func assertCanonicalHostInputs(t *testing.T, imported, programInputs resource.PropertyMap) {
	t.Helper()
	if len(imported) != 4 || len(programInputs) != 4 {
		t.Fatal("Host inputs do not have the complete expected top-level shape")
	}
	for _, key := range []resource.PropertyKey{"resource", "server", "target", "secrets"} {
		importedValue, importedOK := imported[key]
		programValue, programOK := programInputs[key]
		if !importedOK || !programOK || importedValue.ContainsSecrets() != programValue.ContainsSecrets() {
			t.Fatalf("import checkpoint %s differs in presence or secret classification", key)
		}
	}
	for _, key := range []resource.PropertyKey{"resource", "server"} {
		if !reflect.DeepEqual(imported[key], programInputs[key]) {
			t.Fatalf("import checkpoint %s differs from the registered Host input", key)
		}
	}
	var importedTarget, programTarget hostcontract.Target
	var importedSecrets, programSecrets hostcontract.Secrets
	if !decodePropertyJSON(imported["target"], &importedTarget) || !decodePropertyJSON(programInputs["target"], &programTarget) || !decodePropertyJSON(imported["secrets"], &importedSecrets) || !decodePropertyJSON(programInputs["secrets"], &programSecrets) {
		t.Fatal("decode canonical Host inputs")
	}
	importedTarget, importedSecrets = hostcontract.NormalizeTargetSecrets(importedTarget, importedSecrets)
	programTarget, programSecrets = hostcontract.NormalizeTargetSecrets(programTarget, programSecrets)
	if !reflect.DeepEqual(importedTarget, programTarget) || !reflect.DeepEqual(importedSecrets, programSecrets) {
		t.Fatal("import checkpoint Host inputs differ from program inputs")
	}
}
func (h *harness) assertMeasuredCalls(t *testing.T, want []string) {
	h.mu.Lock()
	got := append([]string(nil), h.calls...)
	h.mu.Unlock()
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("provider calls = %v, want %v", got, want)
	}
}
func (h *harness) assertHostOperations(t *testing.T, want ...pulumidisplay.StepOp) {
	h.mu.Lock()
	got := append([]pulumidisplay.StepOp(nil), h.operations...)
	h.mu.Unlock()
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("Host operations = %v, want %v", got, want)
	}
}
func (h *harness) assertOneInspect(t *testing.T) {
	value, err := os.ReadFile(filepath.Join(h.provider.trace, "current", "request.digest"))
	if err != nil {
		t.Fatalf("read inspect digest: %v", err)
	}
	want, err := expectedInspectDigest(h.productionHostInputs)
	if err != nil {
		t.Fatal(err)
	}
	if string(value) != want {
		t.Fatalf("inspect digest metadata differs")
	}
}
func expectedInspectDigest(inputs resource.PropertyMap) (string, error) {
	targetJSON, err := json.Marshal(unwrapFixtureValue(inputs["target"]).Mappable())
	if err != nil {
		return "", err
	}
	resourceJSON, err := json.Marshal(unwrapFixtureValue(inputs["resource"]).Mappable())
	if err != nil {
		return "", err
	}
	secretsJSON, err := json.Marshal(unwrapFixtureValue(inputs["secrets"]).Mappable())
	if err != nil {
		return "", err
	}
	var targetValue hostcontract.Target
	var identity hostcontract.ResourceIdentity
	var secretValues hostcontract.Secrets
	if err := json.Unmarshal(targetJSON, &targetValue); err != nil {
		return "", err
	}
	if err := json.Unmarshal(resourceJSON, &identity); err != nil {
		return "", err
	}
	if err := json.Unmarshal(secretsJSON, &secretValues); err != nil {
		return "", err
	}
	key, err := base64.StdEncoding.DecodeString(revisionKey)
	if err != nil {
		return "", err
	}
	revision, err := hostcontract.TargetRevision(hostcontract.RevisionKey(key), identity, targetValue, secretValues)
	if err != nil {
		return "", err
	}
	frame, err := hostprotocol.EncodeRequest(hostprotocol.Request{Action: hostcontract.ActionInspect, Server: hostcontract.ServerTarget{SSHAlias: "edge"}, Resource: identity, TargetRevision: revision})
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(frame)
	return fmt.Sprintf("operationDigest=%x\naction=inspect\n", sum), nil
}
func (h *harness) assertNoEffects(t *testing.T) {
	for _, name := range []string{"docker-effects", "forbidden"} {
		b, err := os.ReadFile(filepath.Join(h.provider.trace, "current", name))
		if err == nil && strings.TrimSpace(string(b)) != "" {
			t.Fatalf("measured phase emitted Docker effects: %q", b)
		}
	}
}
func (h *harness) assertDockerReads(t *testing.T, want ...string) {
	b, err := os.ReadFile(filepath.Join(h.provider.trace, "current", "docker-reads"))
	if len(want) == 0 {
		if err == nil && strings.TrimSpace(string(b)) != "" {
			t.Fatalf("unexpected Docker reads: %q", b)
		}
		return
	}
	if err != nil {
		t.Fatalf("read Docker trace: %v", err)
	}
	got := strings.Fields(strings.TrimSpace(string(b)))
	var actions []string
	for i := 0; i+1 < len(got); i += 2 {
		actions = append(actions, got[i]+" "+got[i+1])
	}
	if !reflect.DeepEqual(actions, want) {
		t.Fatalf("Docker inspect reads = %v, want %v", actions, want)
	}
}
func (h *harness) assertUnchangedRoot(t *testing.T, before map[string]string) {
	if after := treeManifest(t, h.provider.root); !reflect.DeepEqual(before, after) {
		t.Fatal("runtime state changed during measured phase")
	}
}
func (h *harness) assertNoCanaryLeak(t *testing.T) {
	if strings.Contains(h.provider.stderr.String(), secretCanary) {
		t.Fatal("secret canary leaked to provider diagnostics")
	}
	for _, root := range []string{h.provider.trace, h.provider.root} {
		if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
				return nil
			}
			b, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			// Secret-bearing Runtime env files are the sole deliberate exception.
			if strings.Contains(string(b), secretCanary) && !strings.HasPrefix(path, filepath.Join(h.provider.root, "runtime", "managed", "env-")) {
				t.Fatalf("secret canary leaked to %s", path)
			}
			return nil
		}); err != nil {
			t.Fatalf("secret canary scan failed: %v", err)
		}
	}
}
func treeManifest(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	if err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if relative == "." {
			relative = ""
		}
		mode := info.Mode()
		switch {
		case mode.IsDir():
			out[relative] = fmt.Sprintf("dir:%o", mode.Perm())
		case mode.IsRegular():
			b, readErr := os.ReadFile(path)
			if readErr != nil {
				return readErr
			}
			sum := sha256.Sum256(b)
			out[relative] = fmt.Sprintf("file:%o:%x", mode.Perm(), sum)
		case mode&os.ModeSymlink != 0:
			target, readErr := os.Readlink(path)
			if readErr != nil {
				return readErr
			}
			out[relative] = fmt.Sprintf("symlink:%o:%s", mode.Perm(), target)
		default:
			return fmt.Errorf("unsupported fixture file type at %s: %s", relative, mode.Type())
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	return out
}
func marshalProperties(t *testing.T, values resource.PropertyMap) *structpb.Struct {
	encoded, err := sdkplugin.MarshalProperties(values, sdkplugin.MarshalOptions{KeepUnknowns: true, KeepSecrets: true, KeepResources: true})
	if err != nil {
		if t != nil {
			t.Fatal(err)
		}
		panic(err)
	}
	return encoded
}
func unmarshalProperties(value *structpb.Struct) resource.PropertyMap {
	decoded, err := sdkplugin.UnmarshalProperties(value, sdkplugin.MarshalOptions{KeepUnknowns: true, KeepSecrets: true, KeepResources: true})
	if err != nil {
		panic(err)
	}
	return decoded
}
func fixtureFile(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	return b
}
func fixtureBytes(name string) []byte {
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		panic(err)
	}
	return b
}
func writeFixture(t *testing.T, path string, value []byte, mode os.FileMode) {
	t.Helper()
	if err := os.WriteFile(path, value, mode); err != nil {
		t.Fatal(err)
	}
}
func hostURN() string { return "urn:pulumi:canary::sub2api-environment::" + hostType + "::" + hostName }
func singleHost(t *testing.T, snapshot *deploy.Snapshot) *pkgresource.State {
	t.Helper()
	for _, state := range snapshot.Resources {
		if state.Type == hostType {
			return state
		}
	}
	t.Fatal("checkpoint has no Host")
	return nil
}
func snapshotsEqual(a, b *deploy.Snapshot) bool {
	return reflect.DeepEqual(a.Manifest, b.Manifest) && reflect.DeepEqual(a.Resources, b.Resources) && reflect.DeepEqual(a.PendingOperations, b.PendingOperations) && reflect.DeepEqual(a.Metadata, b.Metadata) && reflect.DeepEqual(a.Snippets, b.Snippets) && reflect.DeepEqual(a.Extensions, b.Extensions)
}
func repositoryRoot(t *testing.T) string {
	t.Helper()
	path, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	for {
		if _, err := os.Stat(filepath.Join(path, "go.mod")); err == nil {
			return path
		}
		parent := filepath.Dir(path)
		if parent == path {
			t.Fatal("repository root not found")
		}
		path = parent
	}
}
func readPort(t *testing.T, reader io.Reader) string {
	t.Helper()
	result := make(chan struct {
		line string
		err  error
	}, 1)
	go func() {
		line, err := bufio.NewReader(reader).ReadString('\n')
		result <- struct {
			line string
			err  error
		}{line, err}
	}()
	select {
	case value := <-result:
		if value.err != nil {
			t.Fatal(value.err)
		}
		port := strings.TrimSpace(value.line)
		if _, err := strconv.Atoi(port); err != nil {
			t.Fatalf("invalid provider port %q", port)
		}
		return port
	case <-time.After(5 * time.Second):
		t.Fatal("provider did not emit a port within 5 seconds")
		return ""
	}
}
func processStart(pid int) string {
	b, err := os.ReadFile(fmt.Sprintf("/proc/%d/stat", pid))
	if err != nil {
		return ""
	}
	close := strings.LastIndexByte(string(b), ')')
	fields := strings.Fields(string(b)[close+1:])
	if len(fields) < 20 {
		return ""
	}
	return fields[19]
}
func stopProvider(t *testing.T, p *providerProcess) {
	t.Helper()
	if p.identity.start != "" && processStart(p.identity.pid) == p.identity.start {
		_ = syscall.Kill(-p.identity.pid, syscall.SIGTERM)
	}
	select {
	case <-p.done:
		return
	case <-time.After(time.Second):
	}
	if p.identity.start != "" && processStart(p.identity.pid) == p.identity.start {
		_ = syscall.Kill(-p.identity.pid, syscall.SIGKILL)
	}
	select {
	case <-p.done:
	case <-time.After(time.Second):
		t.Errorf("provider process did not exit")
	}
}
